### ISSUE TITLE
Map behaves poorly when there are lots of scan points marked on the map

### ISSUE THREAD

**Issue by kbrosnan** [mozilla/MozStumbler#1002]

**Comment by kbrosnan** [comment]
When there are a lot of observations on the map it will start to flicker on panning and eventually will stop displaying new points.

http://people.mozilla.org/~kbrosnan/tmp/mozstumbler-1002/mozStumbler-flicker.mp4

**Comment by garvankeeley** [comment]
Nice stumbling! We set our bar low, which was, keep running when the observation count gets super-high. We are getting close to finding cycles to do a proper fix, not sure if we can get it in for 1.0.
You should see that the new observations draw first, and older ones will flicker, that is expected (albeit ugly) behaviour for now.

Dev Note:
- For 1.0, instead of stopping storage at the point limit, clear out old points and show new ones. 
- the future plan is to draw observation points to the saved rasters directly, instead of rendering as a vector layer
- if ^^ is problematic, store batches of points in R-tree, as we are not currently considering the viewport. This is tricky to combine with MRU concept that we have now.

**Comment by garvankeeley** [comment]
Hopefully fixed in v0.41.0.0
