### ISSUE TITLE
Show number of unique cells/wifis scanned during session in metrics

### ISSUE THREAD

**Issue by cascheberg** [mozilla/MozStumbler#1019]
Those numbers were previously displayed on the main screen and are not available anymore

**Comment by Djfe** [comment]
They got removed to stop displaying unnecessary metrics (could cause confusion if there are two different numbers and you should follow DRY)

**Comment by cascheberg** [comment]
Why did you decide to not hide the other values instead then? I myself found the unique numbers to be more interesting and helpful, and I think they are easier to understand in general.

**Comment by Djfe** [comment]
I didn't decide that that were the devs, I'm just a user of MozStumbler that is interested in open source and wants to contribute later into the project like you do already. I'm still learning Java and I need to look into developing for Android still.

The reason is simple, the other (old) numbers were counting wifi/cell sights that were recorded without a valid/established GPS connection -> so they won't be uploaded

the users would wonder when their sent numbers and score in the leaderboard would be rising slower then the number of recorded wifis and cells

so it makes sense to only show the numbers that will be uploaded later on if there is an internet connection available

**Comment by cascheberg** [comment]
I wasn't necessarily referring to you personally, but to everyone involved :) I was also asking because I could not find the specific relevant push for that change.

So maybe it's a good idead to keep in mind to fix that bug. I think it's not easily possible to compare the non-unique values to leaderboard points at all.

**Comment by Djfe** [comment]
then the wifi/aps should be shown like 5/151 over the map next to the specific icon

took some time but I found the issue about it:
#917

**Comment by cascheberg** [comment]
@garvankeeley I'd be willing to look into fixing this (#132 for unique values) if there is a chance for this to be added back to the UI.
Having different values based on different ways of counting is not great, but I still think the more intuitive and meaningful thing to keep (per default) is to count unique networks.

**Comment by Djfe** [comment]
the numbers on the left are unique already (got changed some time ago from countings to unique numbers)
the only difference is that the left only counts saved wifi/cell networks
and the other numbers include wifi/cell networks that were recorded without a valid GPS signal, which would be too confusing IMO)

what about a devs option to enable showing them?

**Comment by Djfe** [comment]
explained at #1027 that it actually makes sense to show them again because the numbers decrease if you upload during scanning so that ready to sent doesn't represent this session anymore

haven't thought about it before because I was only uploading over wifi -> there was no difference noticeable to me
