### ISSUE TITLE
Reporter loses measurement reports if upload fails with a network error

### ISSUE THREAD

**Issue by cpeterso** [mozilla/MozStumbler#102]
We should probably retry later, but we also don't want to keep retrying the same report if the data itself is some causing the network problem. @hannosch says some web servers, like nginx, limit uploads to 1 MB by default.

**Comment by hannosch** [comment]
Regarding the upload limit: I changed that on our servers, so 10mb is quite fine. But it might still be a good idea to limit the size of each batch upload - at least over mobile connections.

**Comment by flaki** [comment]
Also, it would help to have some built-in UI for initiating uploads when users see it fit (i.e. they have just arrived home, are about to turn off stumbler, so they upload stumbled data first - something along those lines).

In this case, a simple button on the main screen would do the job (if frequent uploads are a problem here, we could limit the use of the button with a timer).

**Comment by ossguy** [comment]
Does this bug mean that if I'm out collecting data without a network connection and then subsequently join a wireless network with a captive portal but don't immediately login to it that I'm likely to lose data (presumably because MozStumbler would try to upload when it detects the connection but then fail due to the captive portal)?  Or is it better/worse than that?  For example, if one is out collecting without a network connection, will the reports just fail to upload and be lost because there's no connection?  In this case, would the UI still show the number of locations and APs scanned, even though they've been lost and are unable to be reported?

Sorry for the barrage of questions.  I'm mainly trying to figure out when it is useful for me to be running this app.  I spend a lot of time away from network connectivity while scanning (usually because I'm outside my home country and don't have data roaming), but I'd still like to contribute that information (ie. by having the app cache its data until I arrive back at my room and connect to wifi so it can upload).

**Comment by cpeterso** [comment]
@ossguy: Thanks for asking! I should have closed this bug report. @dougt fixed this bug in PR #244, which is included in the MozStumbler v0.8.0 release. With that fix, the stumbler will avoid uploading if the network is disabled, but if the stumbler tries to upload and fails, then it saves those measurements to be uploaded the next time we try. So you should now lose any measurements. If you see otherwise, please report a bug. :)
