### ISSUE TITLE
Rename “Sent (all time)” to “All sessions”

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/MozStumbler#1027]
In the metrics panel, rename “Sent (all time)” to “All sessions” to make more consistent with previous “This session” heading.

**Comment by ryanfeeley** [comment]
(Note the lowercase S in sessions)

**Comment by garvankeeley** [comment]
Thx, it is

**Comment by garvankeeley** [comment]
The stats are actually the sent data. All sessions implies the current session is included in this data, which it isn't.
![screenshot_2014-10-22-23-24-38](https://cloud.githubusercontent.com/assets/5495083/4747932/23d226e8-5a65-11e4-82c9-8b2baec67b06.png)

**Comment by Djfe** [comment]
actually we should add the wifi and cell counts of the current session again like @cascheberg proposed already (#1019) because if an upload takes place during the session/scan time than the ready to send section doesn't represent the number of collected wifis and cells in this session any more

it only represents them if the user is using "Upload only on Wi-Fi" and hasn't connected to a Wi-Fi since scan start, yet.

EDIT: or we could merge this session and ready to send by displaying it like: 4/50 cell networks
4->ready to sent
50->this session
this would save some space and thereby simplify the metrics section but could potentially cause confusion
