### ISSUE TITLE
Philippines mapping

### ISSUE THREAD

**Issue by grrrrr** [mozilla/MozStumbler#1035]
apologies for this as I know it is not an issue per say but more a question and not sure of a mozstumbler mailing list to ask on.

Can anyone explain the star like mapping that occurs coming out from Manila and into the sea?

https://location.services.mozilla.com/map#7/14.881/120.795

**Comment by Djfe** [comment]
ok this looks strange and cool at the same time but I don't have a clue why it is happening :)

**Comment by hannosch** [comment]
That's an old and unsolved problem, first described here: https://groups.google.com/d/msg/mozilla.dev.geolocation/biwiie__M10/koQQW2BcFsQJ (short version: bad imported data). An issue on the server side would probably be more appropriate for this: https://github.com/mozilla/ichnaea/issues

**Comment by Djfe** [comment]
is it possible to analyse the available data in that part of the database for possible patterns to filter out in a convenient way or will this problem eventually solve itself if new data gets imported for the same cells/wifis so that the blocking algorithm for movement can first delete those entries and later put them in again if further uploads confirm it's "new" position?

or is that not possible because of data skew different from only lat/lon positions? (->data is completely messed up: cell and wifi ids as well)

**Comment by hannosch** [comment]
There isn't an easy way to clean the map up. The problem is that the map only shows the positions where observations where taken. But we don't retain the observations in the online database, but dump those to files (Amazon S3). So we cannot conveniently query that data again without going through it all.

What we have in the online database is just the aggregated positions of the cell/wifi networks. Those positions should have been corrected via the movement detection logic and via new and better observations getting in.

Maybe we could filter all the map points against the aggregated cell/wifi positions and filter those out which aren't in the range of any of those networks. That might help with some of the far out data in the ocean.
