### ISSUE TITLE
EOF error in log

### ISSUE THREAD

**Issue by Djfe** [mozilla/MozStumbler#1038]
Maybe another issue you want to fix before the 1.0 release/milestone:
![log](https://cloud.githubusercontent.com/assets/5685512/4699652/d60d1378-5843-11e4-9a17-07352e033936.png)

cannot provide any information on how to reproduce this, yet, because this was my first run since a month or so ago that really worked (using 0.40.4.0).
Happended at the end of the run during upload

maybe I'm able to recognize some behaviour/make a cat log the next time it happens

btw. I have a question: is this uploaded together with crash logs, or are crash logs, crash logs only?
and are those crash-logs being uploaded during/after uploading reports?

**Comment by garvankeeley** [comment]
This looks like a network error, which should be ok, it will retry the upload.

@crankycoder can answer the upload crash reports question. They are independent of the scanning report uploads from what I see.

**Comment by Djfe** [comment]
I thought EOF mean EndOfFile so I thought it was about the db.
this screenshot was taken in 0.40.4.0 btw.

**Comment by crankycoder** [comment]
Thanks for catching this.

@Djfe what device and version of Android are you using?  We had a problem in Stumbler 0.30 where HTTP connections were not properly closed because of an Android bug, but I haven't seen this myself.

I've just added a patch to make all error logs include a stacktrace so that we can debug this here: https://github.com/crankycoder/MozStumbler/commit/c3532553e723efbbd2d7727a31012351e981f788

In anycase, the 0.41 release includes better error checks around uploading so upload errors will not cause data to be lost. It will just be retransmitted unless you get an actual HTTP 400 error from the server.

**Comment by Djfe** [comment]
I will report here if I catch issues again in 0.41.0.0
Android Carbonrom http://forum.xda-developers.com/showthread.php?t=2575425 nightly 13 (Kitkat 4.4.4)

(if there are bugs in Android they might have been fixed in the upstream already->the page above is an unofficial port, it doesn't get updatet as often as the official versions, it was official before, but it's only one developer that integrates device specific stuff)

gonna update to nightly 14 this weekend

**Comment by Djfe** [comment]
This is what it looks like in 0.41.0.0:
![2014-10-23 14 40 30](https://cloud.githubusercontent.com/assets/5685512/4757926/0c499b02-5adb-11e4-9d62-bf1dfbbba262.png)

the cause here was different though:
I was riding a bus and driving past my university so that my device connected to the university wifi (eduroam) and started uploading some of the reports even got uploaded but others seemed to have ended in HTTP/Connection Errors because my device was again too far way from the wifi to continue uploading

**Comment by garvankeeley** [comment]
Closing, this sounds like a benign network error. We certainly won't delete the stumbles because of this, and will retry later to send.
