### ISSUE TITLE
Investigate network scanner scanning frequency

### ISSUE THREAD

**Issue by cascheberg** [mozilla/MozStumbler#1055]
Currently the frequencies of GPS position updates, cell scanning, and wifi scanning are configured independently from each other. The `WiFiScanner` has `WIFI_MIN_UPDATE_TIME` = 5000ms and the `CellScanner` has `CELL_MIN_UPDATE_TIME` = 1000ms, while the `GPSScanner` requests location updates after 10m movement occured and at least 1s passed (#1039 -> 30m, 2s).

I would assume that based on the range of different network types, wifis need to be scanned much more frequently than cells, because a wifi might not be visible anymore after moving >10m, while cells can potentially span several kilometers. This makes sense even when only having observation points every 30m.

If you want to scan for wifis every ~15m at 50km/h, you would need to scan every 1 second.
I wonder if it would be best to hook up the network scanners to the GPS too, to start each scan based on passed time and movement as well.

**Comment by hannosch** [comment]
I think a very early version of MozStumbler did start off a cell/wifi scan whenever we got a GPS location fix. That didn't work all too well, since the underlying OS and hardware typically don't allow arbitrary short scanning intervals for these. And they tend to actually give you some cached version of data, so what you are getting is rarely data that represent what you actually have around you "now".

We moved to the separate scanning model as a result. The idea being that you get data from each scanner as often as possible, and than try to match them up by what was available at roughly the same time.

This isn't ideal and not very deterministic, but was better than the old version. It certainly can be improved. Just giving some historical context here :)

**Comment by cascheberg** [comment]
Thanks for that!

I already mentioned this in #1039: I set the wifi scanner to scan every second, and the scan results could vary each second, so it does not seem as if I get the very same cached results for a longer period of time (using a Nexus 4). On the other hand, I do not see a benefit in requesting cell scan data every second, assuming that you could save some energy by using lower frequencies.

I was thinking of having GPS related thresholds for the network scanners the way it exists for the GPS scanner, but each with different values, and then (just as it's done now) assign the scan results to whatever is the current observation.

**Comment by Djfe** [comment]
the situation might have changed and the caches of the OS might deliver more accurate data (with better hardware underneath)

I agree that we should scan cells only every 2 seconds or less (happens on my phone that it switches between 1 (connected) and x (available) cells every second, cause the interval is probably too short
wifi every two seconds sounds reasonable, too

about every 30ms: I would prefer every 15 oder 20m -> it's more accurate

is there a way to reduce server stress on the server side? -> only save data -> process later/continually with a cron job, when capacity is free

**Comment by cascheberg** [comment]
@hannosch I am trying to figure out how things work. The current accuracy is 30m, before it was 10m. Does MLS benefit from collecting **cell only** observations at these high accuracies?

**Comment by hannosch** [comment]
@cascheberg We haven't really looked into collection intervals and how much data is actually really useful and by how much it could be reduced.

That said, there are some pico and femto cell networks around for example transportation hubs which can be just 100 meters in size. On the other hand we have cell sizes of 100 km in rural areas.

Personally I'd be more interested in getting a better handle on time synchronization between the different sensor data points, so the GPS/cell/wifi data collected in one record actually are all about the same time/place.

**Comment by Djfe** [comment]
might be because of #1004 but I see lots of cell-only reports nowadays when moving too fast

the reason could be that #1004 blocks duplicates now and that we only scan every 5 seconds...

I was riding a bus here so I was driving at more than 10m/s

![2014-10-23 14 36 14](https://cloud.githubusercontent.com/assets/5685512/4755797/6a869c8c-5ac8-11e4-813e-9e6eb3f90cb4.png)

I would like to have kinda synced intervals (if there is repetition then in specific rhytms)
the server might need to know about this, too (if duplicates are blocked...)

one question that pops up here, too, is whether we want to reduce scanning intervals in power saving modes (new feature that might be integrated some day, depends on: #21 #261 #333 )

**Comment by garvankeeley** [comment]
@hannosch "Personally I'd be more interested in getting a better handle on time synchronization between the different sensor data points, so the GPS/cell/wifi data collected in one record actually are all about the same time/place."

Reducing the scanning interval from 1s to 2s will reduce the accuracy of the scans, because it creates a larger scanning window. The trigger to close the scan window is the next GPS.

**Comment by cascheberg** [comment]
@Djfe I am pretty sure that this is not caused by #1004, I noticed this several times in the past already.
I think this happens because wifi data only gets added to the current observation every 5 seconds, while observations may happen every 2 seconds. This means that, if you travel >30m in 2s to trigger GPS position updates, there will always be 2 observations (0-1 otherwise) without wifi data.

**Comment by Djfe** [comment]
well already running causes blue points to appear... (doesn't need to be a vehicle)

I think that the cell scanning intervall is too short anyway though -> it returns a cell everytime, yes, but often it's only the cell I'm connected to and no neighbouring cells... (it switches between connected and neighbouring cells every second->seems like it takes longer than a second to get all neighbouring cells scanned)

**Comment by cascheberg** [comment]
I'd think that triggering one scan only every time the `GPSScanner` reports a new location would be a good solution. Is it worth another try although @hannosch mentioned some problems with that in the past?
The current implementation does not seem to scan at the fastest possible rate, there are fixed values of 1 and 5 seconds. I found some [code](https://android.googlesource.com/platform/frameworks/opt/telephony/+/android-4.4.4_r2.0.1/src/java/com/android/internal/telephony/ServiceStateTracker.java) that looks like cell data is cached for 2 seconds (`LAST_CELL_INFO_LIST_MAX_AGE_MS`), and at least on my Nexus 4 there are no apparent problems with scanning wifis every second.
The benefits would be that the scan is happening as close as possible to the actual location. Furthermore, since GPS uses [`requestLocationUpdates`](http://developer.android.com/reference/android/location/LocationManager.html#requestLocationUpdates%28long,%20float,%20android.location.Criteria,%20android.app.PendingIntent%29), you save some energy because there are no scans when the device hasn't moved. Only GPS is active then, and the API mentions some power saving optimizations in the location provider itself, based on the time and distance parameters. You could even add a preference to allow the user to configure the time between updates from ~2 seconds to up to several minutes, which currently can not be realized.

**Comment by hannosch** [comment]
From what I remember, the problem with WiFi scanning is, that the frequency of API calls, does not reflect how often the underlying hardware actually gets new information. Typically it takes a couple of seconds for the chips to cycle through all available frequencies and find all available networks. That is if they do active probing. If they just do passive listening for the beacon frames from the access points, that might even take longer. The chipsets usually do some kind of uncontrollable caching and when asked for the current list of all WiFi networks, will reply with a cached result covering some past time range. Especially networks you have associated with tend to show up in these cached results long after they have been in reach. I've seen networks be reported as present minutes after you've left their maximum possible range. And on top of this the OS itself might do some additional caching.

There are a good number of uncontrollables and variables in this which depend on the exact hardware, driver version and OS version. Which makes it hard to test this.

That said, I don't think we have done extensive testing and simulation to optimize this code, so there might well be simple things to improve in it.

**Comment by Djfe** [comment]
this could be tested on more devices, on cpeterso devices' there were no differences but on others there might be:
https://github.com/mozilla/MozStumbler/issues/40

**Comment by Djfe** [comment]
btw. if the guy here is correct(xenonite), then it only takes 0.7 for passive scanning:
http://stackoverflow.com/questions/5958715/what-is-the-difference-between-active-scan-and-passive-scan

maybe active scanning also probs for hidden SSIDs (Jadiyappa)

interesting, too:
https://groups.google.com/forum/#!topic/mozilla.dev.geolocation/6O1KxH2qupI
