### ISSUE TITLE
Log Activity: spamming network unavailable messages

### ISSUE THREAD

**Issue by garvankeeley** [mozilla/MozStumbler#1112]
My log gets filled with this
![screenshot_2014-10-23-22-10-25](https://cloud.githubusercontent.com/assets/5495083/4774219/0a13e4fc-5bab-11e4-8430-7a9335b55fee.png)

**Comment by Djfe** [comment]
Seeing something similar in 0.42.0.0:
![2014-10-24 22 19 04](https://cloud.githubusercontent.com/assets/5685512/4777694/84fdb1c8-5bd5-11e4-9e11-e3562a0bfdbe.png)

Something similar (or different) in 0.41.0.0 from today:
![2014-10-24 19 05 56](https://cloud.githubusercontent.com/assets/5685512/4777691/788b4cca-5bd5-11e4-9984-0caabe1fb235.png)
![2014-10-24 19 10 48](https://cloud.githubusercontent.com/assets/5685512/4777692/7b1f4392-5bd5-11e4-812f-1e33692d4a77.png)

EDIT: about 2nd and 3rd screenshot: MozStumbler was running while I was in a building->no GPS fixes (that's why so many were next to each other), I wasn't connected to the internet and the map was set to no map, the MLS layer was activated though, so I'm wondering why those errors appeared
if it's the MLS layer then there is a check missing somewhere that needs to checks whether an internet connection is available before trying to use it before loading tiles

**Comment by garvankeeley** [comment]
https://github.com/mozilla/MozStumbler/pull/1118
