### ISSUE TITLE
Screen Off Scanning: Reports doesn't increase when the screen turned off. 

### ISSUE THREAD

**Issue by garvankeeley** [mozilla/MozStumbler#1124]
Have this report on the geolocation list. If anyone else is experiencing the problem please let us know what device, perhaps a dev can get their hands on a particular device and figure out a workaround.

nevzorovn@gmail.com wrote:

I can't say since  ver, i think 0.40.0.0 no scanning when screen is off, and turned on screen decrease battery life in 3 times. I saw it on two phones: Lenovo A789 and THL W100S. The number of scanned points dosn't increase when the screen turned off.

**Comment by Djfe** [comment]
For me I often see, that my phone doesn't reconnect to cells while driving in a tray -> after a certain time with my screen off I get only purple dots and then there are places without any dots (since there is no wifi either)

For me it only happens for cell, wifi scan seems to work correctly

if my screen is on my phone seems to try to connect to a cell tower
(I have my data connection over cell disabled, so there might be no reason for my phone to keep a complete cell connection!?)

I don't have a screenshot of it right now though and it might have to do with the frequent cell change while riding a train. -> the handshake between cells might not work that fast
next time I will ride a train I will have a newer version of my OS anyways so it might have been an issue that is fixed now)

**Comment by crankycoder** [comment]
I've seen the same behavior on a Nexus 4 running stock 4.4.4, no SIM card only doing WiFi scanning.

After the screen was turned off for ~30 minutes, the stumbler stopped collecting data. No other apps were running (or even installed other than the stock apps) so I don't think the app was killed off.

Unfortunately, I wasn't persisting the debug logs.  This was on 0.42 of the app.

**Comment by garvankeeley** [comment]
Comments from mailing list:

The 0.30.0 works fine on both phones, newer versions(and 0.99 too)
with turned off screen scan only wi-fi cells. On map prints only
magenta rounds on all way.
2014-10-28 1:47 GMT+05:00 Nikolay Nevzorov nevzorovn@gmail.com:
0.41.00 on THL W100S seems work with off screen. Lenovo A789 no GPS
fix from window. Tomorroy i'll test it from car and write result.

**Comment by crankycoder** [comment]
Closing as this was filed before a lot of UI work was done.
