### ISSUE TITLE
feature request: latitude 

### ISSUE THREAD

**Issue by ag88** [mozilla/MozStumbler#1136]
can mozstumbler incorporate features of the retired _google latitude_?

https://support.google.com/gmm/answer/3001634?hl=en
http://en.wikipedia.org/wiki/Google_Latitude

however that may mean that mozilla may need to run an additional service on top of exlsting Mozilla
Location Service. 

for a start it may be based on GPS as cells & wifi are growing and not yet ready for prime time.
however, this would make mozstumbler apps _useful_ and more people would use it to contribute anonymous tower locations

**Comment by garvankeeley** [comment]
What specific feature you would like from latitude?

**Comment by Djfe** [comment]
I'm not sure whether that even makes sense anymore:
most of the users will have updated to the newest version of maps

quotation from the website you linked above:

> Google Latitude was retired on August 9th, 2013. Products retired include Google Latitude in Google Maps for Android, Latitude for iPhone, the Latitude API, the public badge, the iGoogle Gadget, and the Latitude website at maps.google.com/latitude.

**Comment by ag88** [comment]
here is an old blog that says something about google latitude
Locate your friends in real time with Google Latitude
http://googlemobile.blogspot.sg/2009/02/locate-your-friends-in-real-time-with.html

it is really not a maps feature, more so than that it is more of a service run from a server which allow location info to be broadcasted to a (subscribed) group of people. i'd think it is quite possible to do this via xmpp(jabber) but essentially quite a bit of application functionality is needed on the mobile device to support it as well.

**Comment by hannosch** [comment]
From a broader Mozilla perspective, we have two projects that do some of the latittude work. One is the Firefox Hello project (codename: Loop, https://wiki.mozilla.org/Loop) which allows cross-platform communications and includes the technical bits for an address book ("social graph") and "presence" (in order to make a webrtc call to someone, we need to be able to figure out if that person is online and what their IP address is to initiate a direct connection). So this allows one to define whom you want to see and a way to contact them.

The other project is the Firefox OS only "Find My Device" project (https://wiki.mozilla.org/Gaia/Find_My_Device) which is about finding your own device, locking it or erasing user data in case of theft. This project needs to be able to figure out the GPS location of a remote device.

Personally I think a "find my friends" project would be a better fit as an extension for either one of these projects. Instead of Mozilla building something specific for Android only.

**Comment by Rondom** [comment]
Maybe OsMo fits your needs. There is a dedicated client for Android and an Osmand plugin.
http://osmo.mobi/
