### ISSUE TITLE
How long should I wait for new blue to appear?

### ISSUE THREAD

**Issue by SteveALee** [mozilla/MozStumbler#1168]
I have used for several days now and my newly stumbled routes have not appeared in blue yet.

**Comment by VolMi** [comment]
That's strange. The server updates the map within each European night. But I haven't checked in the last days (since I live in a completely blue environment already).

Is your upload queue empty? Do you have a nickname and can check if you got points for your stumbles? If you got the points, the data is there and it might be some server issue.
Did you check the online map in the browser? -> Maybe local caching of map tiles in the app prevents an update.

**Comment by SteveALee** [comment]
Thanks, I just checked and they are appearing now. I'll put it down to caching as you suggest. Lets see when last night's stumbling appears. Plus out walking the dog this morning

My nickname is slee, right near the bottom of the table :)

**Comment by garvankeeley** [comment]
The generation is once daily. I agree the feedback cycle for this feels a tad long, as depending on the times you stopped on day 1 and check on day 2, it can seem like the data isn't showing up.

**Comment by edt-xx** [comment]
Day three here and points from day one still have not appeared.  They are accumulating under my nick though...

**Comment by garvankeeley** [comment]
Can you try App Info -> Clear cache?
This should force the coverage tiles to reload and tell us if the bug is on the server or on the Stumbler.

**Comment by edt-xx** [comment]
Clearimg the app cache helped.  Now I see them on the map in the app.  What
is strange is they were not showing on the
location.services.mozilla.com/map# site either.  Now they are.
Thanks

**Comment by garvankeeley** [comment]
This is a bug, we should keep an eye on this. The tiles are supposed to refresh automatically.

**Comment by garvankeeley** [comment]
I think this is all sorted out now.
