### ISSUE TITLE
Lost reports after a crash

### ISSUE THREAD

**Issue by SteveALee** [mozilla/MozStumbler#1174]
I was walking about so no wifi connection and thus also no auto upload (as settings at default of off) when I got the dreaded 'Sumbler had problems and is closing' error. I had just launched GMail and my phone is low on resources s oI expect that killed Stumbler.

However when I restarted stumbler all my reports since starting Stumbler had disappeared from the map and the stats were all at 0. It seems reasonable to assume they were lost.

Is it possible to persist them in less volatile memory? Or were they reset on startup? Whatever, I could imagine the annoyance if it crashes after a long time and many records are lost. Some people are serious about these league tables :)

**Comment by Djfe** [comment]
Which device and what version of Mozilla Stumbler were you using?

As far as I know reports only get saved every 50 reports or something like that.

Maybe that can be improved, so that they get saved every x seconds.

This limitation has been introduced together with the file-based database (was needed for the integration into Fennec (Firefox for Android)), because Garvan wanted to reduce the number of disc accesses.
Without crashing no reports are lost (they get saved if you turn off scanning and close the app).

**Comment by garvankeeley** [comment]
Correct, every 50, or if stumbling stops, or if some timeout (I have to check how long).

**Comment by SteveALee** [comment]
Sorry, Android (old HTC One S) and latest version from Play (assuming it auto updates).
I guess I was unlucky and it crashed just under 50 reports.

I understand the engineering compromise and it seems good to me.

**Comment by garvankeeley** [comment]
@SteveALee can make sure crash reporting is on? It is in the developer setting right now, we need to bubble that up.

We aren't handling low memory notifications from the OS yet, and we should, I'll add a bug for that. 
#1176

**Comment by SteveALee** [comment]
@garvankeeley Done

**Comment by crankycoder** [comment]
Low memory is now handled all over the place and we haven't heard of anyone losing data after a crash for a while.
