### ISSUE TITLE
Add a "file a bug" button

### ISSUE THREAD

**Issue by crankycoder** [mozilla/MozStumbler#1182]
We frequently get bug reports where we inevitably ask for device and rom info.

We should really be able to file bugs from the device which captured this information for us.

Maybe implement this as a hook into ACRA?

**Comment by SteveALee** [comment]
I tried to supply info from the log but could not cut and paste it.
I then tried a screen dump but after switching to desktop GitHub in Firefox for Android it reset back to an empty mobile form after I tried to insert the image.

**Comment by Bugsbane** [comment]
Yes, please. I just accidentally filled what I thought was a Stumbler big on the ichnara project because I couldn't find a bug report link in Stumbler. Then I tried to insert a screenshot, to get the same form blanking bug in GitHub mobile, then I tried to copy and paste the log, but found that you can't select text in the log... just like the previous commenter.

**Comment by SteveALee** [comment]
So glad it is not just me! :)

**Comment by johnnyxh** [comment]
I've been working towards adding this feature today, mostly on the UI portions for a new bug reporting activity. I've been meaning to use ACRA for this by taking in bug title/description/reproducibility fields from my new bug reporting activity and stuffing it into the CUSTOM_DATA field, then I can manually send a "crash report" with just that data. Problem is I don't know where these reports are sent (or if I even have access to them) to see if they are working properly. I guess I'm not too sure how I'd test to see how this works without having to make my own destination for these ARCA reports.

**Comment by crankycoder** [comment]
@johnnyxh have you tried installing the ACRA server on your own machine?  Standing up an Acralyzer server is not too bad.     Can you try the instructions over here?  https://github.com/ACRA/acralyzer/wiki/setup

**Comment by johnnyxh** [comment]
@crankycoder I set up my own ACRA database on Cloudant along with Acralyzer, and tried it out. It works decently well, though at first glance these look like regular crash reports. The stack trace sets apart regular crashes from bug reports, since the stack trace entries contain "Requested by the developer". Not sure if this is a good enough distinction, but you can see the bug title/description/etc fields under the custom field along with the usual information sent in an ACRA report.

**Comment by Bugsbane** [comment]
Sweeeeeeeeeeeeeet. :)

**Comment by cascheberg** [comment]
This issue is fixed and should be closed.
