### ISSUE TITLE
Detect if no SD card is available

### ISSUE THREAD

**Issue by crankycoder** [mozilla/MozStumbler#1183]
Some devices only have android internal storage available.  In this case,  we can't write tiles to storage or write stumble logs. 

We need to display a message to the user that the stumbler requires some kind of external storage. 

The current user experience in this case is that the stumbler inexplicably doesn't work. 

We can only test this by trying to write to storage and getting an error.  If no storage is available,  getStorageDir()  and getCacheDir()  may still return valid paths.

We can test this  in simulator or with the Galaxy Fit in the Toronto office.

**Comment by garvankeeley** [comment]
I developed the code on a no-sdcard simulator, it ran fine, I don't think this is a bug.

**Comment by crankycoder** [comment]
We're seeing this no tiles behaviour in at least the Galaxy Fit running android 2.3 with no SD card.

**Comment by garvankeeley** [comment]
That is because changes to OSMDroid have somehow caused this. This works with the unmodified OSMDroid in our code (with the 1 modification for overriding the tile storage directory).

**Comment by garvankeeley** [comment]
SmartFSProvider.java: so far, if I change checkSdCard() to set mSdCardAvailable to true, this works again. Will check with @crankycoder for opinion on this.

I don't see the value of this check, because we override OSMDroid's default behaviour with TileFilePath.java, which tricks OSMDroid into using our chosen directory path, which is either sdcard if one is available, or the main storage if that is available.
