### ISSUE TITLE
Can this run on a Firefox OS phone? 

### ISSUE THREAD

**Issue by znmeb** [mozilla/MozStumbler#1222]
I've got two phones - an Android phone and a Firefox OS Flame. Can this run on the Firefox phone?

**Comment by Djfe** [comment]
MozStumbler is an app that is developed specifically for Android
the service of the app is used in fennec (Firefox for Android)

Firefox OS apps that do pretty much the same and report scans to MLS):
https://github.com/clochix/fxstumbler
http://pocz.org/ac/projects/mvdstumbler/mvdstumbler.html

You need to install them manually using the .zip files though since they need specific rights to access the wifi data of your phone and perform scans, therefore they are not available on the marketplace, because they would need to be signed or something like that.

**Comment by hannosch** [comment]
For Firefox OS there are three different kind of apps. https://developer.mozilla.org/en-US/Marketplace/Options/Packaged_apps#types_of_packaged_apps has the long overview.

On FxOS some API's are restricted and need the users consent in order to be accessed by an app. A webapp cannot access most of them, a privileged app (hosted on a marketplace and signed by it) can ask for specific permissions (access to camera, contacts, etc.), similar to the typical Android/iOS app. An internal certified app is one shipped on the phone by default (either via the OS or the carrier partner).

Currently only those internal certified apps can access the API's to ask for cell and wifi information, as there is currently no fine-grained permission model for those areas yet (https://developer.mozilla.org/en-US/Apps/Build/App_permissions). A patch to introduce more fine-grained permissions for WiFi access is being worked on and might land for Firefox OS 2.2 (https://bugzilla.mozilla.org/show_bug.cgi?id=934292).

**Comment by Djfe** [comment]
definitely a better and more detailed explanation than my one.
Thanks for chiming in @hannosch :)
