### ISSUE TITLE
Stumbling without data enabled fails to upload any/most data

### ISSUE THREAD

**Issue by sole** [mozilla/MozStumbler#131]
I did a wonderful walk yesterday with data disabled, where I caught hold of almost 3000 wifi access points and then enabled data to upload before my battery died.

When I came home I had only 1 point.

Today I walked again with data disabled and enabled it when reaching the office then pressed stop to upload and I had only 7 points.

On the way back I decided to keep data enabled all the way and voila, in a shorter path I got about 200 points.

I'm using a Nexus 4. Can I help with anything else?

**Comment by cpeterso** [comment]
hi @sole, that must be very frustrating!

The "points" on the leaderboard are a little confusing because they are the number of locations scanned, not the number of WiFi access points. (@hannosch is working on creating separate leaderboards for locations and access points.)

Do you recall if both the "Locations Scanned" and "Wi-Fi Access Points Scanned" counters were working. If the GPS signal is weak, MozStumbler might be (visually) counting WiFi access points it sees but not saving them for upload. I need to double-check.

**Comment by sole** [comment]
Hey that's fine. This is beta software! I know there're risks :-D

I can redo the walk anyway.

I remember that both numbers were increasing, which was very promising! I always tried to walk under a clean sky i.e. avoiding trees or covered passages. The average number of visible GPS satellites was 9-13 which seems quite good? But then I'm a newbie on this so maybe it's not that good.

**Comment by cpeterso** [comment]
9-13 GPS satellites is very good. Android usually doesn't send a "you are here" GPS event to the stumbler until the phone sees at least 7-8 satellites. We should probably fix the UI so it is clearer.

**Comment by Djfe** [comment]
could you please change the the gps display so that it shows two numbers:
5/9 satellites or something like that
this way you can see more easily how many satellites you are synced with

(example: GPS Status & Toolbox: https://play.google.com/store/apps/details?id=com.eclipsim.gpsstatus2&hl=de , it shows fix/satellites)

I hope you understand what I'm trying to say
I'm not sure how to explain this correctly but you should understand what I'm talking about if you take a look at the app ;)

**Comment by cpeterso** [comment]
I think these data loss problems should be fixed in the latest MozStumbler v0.13.0.
