### ISSUE TITLE
We should only increase WiFi access point count when we have a GPS fix

### ISSUE THREAD

**Issue by cpeterso** [mozilla/MozStumbler#132]
This will prevent confusion like issue #131 where the number of WiFi access points appears large, but the number of locations is small or zero.

**Comment by dougt** [comment]
@cpeterso what count?

**Comment by Djfe** [comment]
Are you talking about the number of scanned aps and towers increasing even without a GPS fix?

Actually all counters get updated only right now if there is a GPS fix (a real update only happens if mainactivity gets recreated #404)

So it would be nice to see the counter getting updated even without a GPS fix if you want to test the location service (at least the visible counter)

Since the upload process has been changed, there shouldn't be confusion any longer as the upload observations dialog doesn't show observations in the queue then

A replacement for the last known location could do the trick as well ("no GPS fix")
Look at the 2nd idea of #280.

**Comment by Djfe** [comment]
@garvankeeley this is kinda fixed now since we only show visible counts and the queue
->there is no general number anymore that is increasing, even though entries aren't filled into the database
