### ISSUE TITLE
add explicit high-power mode

### ISSUE THREAD

**Issue by VolMi** [mozilla/MozStumbler#1386]
There are a lot of [efforts to limit power consumption](https://github.com/mozilla/MozStumbler/labels/Power%20Consumption) to "reasonable" values.
However, there are situations where I just don't care and I'd rather find more networks than saving power: Driving fast with a 5s scan interval means that you miss most WiFi networks.

My wish for an option:
-  [x] smart tradeoff: power vs. thoroughness
-  [ ] high-power mode if charging
-  [ ] high-power mode

We are currently locked in the first option. It would probably make sense to default to the second option or at least offer it.

High-power mode could dispense with motion detection and increase the scanning frequency. I find both mostly annoying, because motion detection only works to detect the _end_ of motion; I then have to start scanning manually. The low scanning frequency does only make sense if you are walking. Even cycling is too fast: 5s · 20 km/h = 28m

**Comment by lua86** [comment]
I would so love such a feature. So before that, it would be needed to NOT hardcode scanning time.

**Comment by garvankeeley** [comment]
Not a bad idea to add a developer setting for this rate. In my experimentation, the startScan() rate had very little effect, but it could be specific to my hardware. The code currently calls the wifi startScan() every 5 seconds, but the call is asynchronous, thus the wifi subsystem may be running completely independent of this (in terms of scan timing), and that call may be just keeping the wifi scanning from stopping.

**Comment by cascheberg** [comment]
Some discussion about configurable scanning frequency is in https://github.com/mozilla/MozStumbler/issues/1055#issuecomment-61025494
But there should not be any negative effects on the data accuracy here as long as you do not decrease the GPS position reporting frequency.

**Comment by Djfe** [comment]
What could be possible is: collecting all streams independently (wifi/cells/gps/motion data)
and then interpolating the positions of the wifis and cells by taking a look at time, position and speed when they were recorded
interpolating should happen between the points where new networks appear to estimate the exakt switching point

depending on whether this calculations are made on the device or the server we would need to change the API and I'm not sure whether devices are powerful enough for doing it (while scanning at least because of the map)
doing it client side would increase privacy because the client still only needs to send the month the track was recorded in, doing it server-side would require exakt times and driving speeds which would allow reconstructing tracks easily and add further network traffic

**Comment by VolMi** [comment]
I found the hint to #1055 quite insightful, thanks.

This request is mainly meant in a more abstract way, not because of my great oversight but my thin understanding...
I seemed to comprehend that the power saving efforts came at a price of reduced `No. of WiFis found` / `GPS accuracy`. I would not mind the density of GPS positions but it seemed to me that the recent stumbler releases found less WiFi networks when I move fast than did earlier versions. That's quite subjective though.

That proposed option was meant as a cheap way out of possible precision restrictions in case power consumption really does not matter. Like: turn all internal configs to the precision side of the compromise.
If it's true that forced WiFi updates <5s don't change anything, that could be meaningless, of course.

**Comment by Djfe** [comment]
Ok so that's your issue.
well the reason for that is:
the GPS update only saves scans every second and only every 30meters

it was 10meters before and got reduced to every 30meters to prevent extra server-side stress on the play store release
(up to 1/3 less traffic per person)

I'm not sure though maybe it got reset to 10 already
hanno said once already that the server-side stress isn't too high so that the number of scans could be increased again

**Comment by garvankeeley** [comment]
It is still at the 30m/2s rate.

**Comment by Djfe** [comment]
Should I make a PR?

**Comment by cascheberg** [comment]
Increasing the rate of reported GPS positions should have no influence on the number of found wifis, because those are scanned independently every 5 seconds, as mentioned. But it should increase data accuracy.
And still, a pref to increase wifi scan frequency would be interesting.

Something else to note: certain earlier releases displayed the number of total wifi observations, in contrast to the currently displayed number of unique observed wifis. This could lead to the number being several times higher than it is now (especially when moving slowly).

**Comment by Djfe** [comment]
But increasing the rate by decreasing the number of meters down to 10 should increase it a lot (especially if you are walking)

we could leave the number of seconds at 2 but I still think 1 second is better

@cascheberg note is definitely another thing that could have caused confusion

a beta build that allows experiencing with these values could be interesting
->driving a few kilometers in a car/on a bike using the same route and then comparing the values should help with comparing what the best settings are
