### ISSUE TITLE
Scanning pauses when I stand still, but doesn't resume when I start moving

### ISSUE THREAD

**Issue by kparal** [mozilla/MozStumbler#1394]
Some time ago there was a Stumbler update which was supposed to pause scanning when you stopped moving, in order to save battery. That seems to work, however, since that time, I experience a large unscanned gaps in my travel routes. If I stand still for a while (e.g. waiting for a tram, or filling gas in a car), Stumbler turns off scanning. But when I start moving, it does _not_ resume scanning. It resumes only when I manually wake the phone. Which can be hours later.

Yesterday, I experienced a 30 minutes scanning gap, just because I waited a few minutes for a tram.

I'm not sure whether this lack of reliable resuming is on purpose or not, but it makes the app much less usable for me. I turn Stumbler on just ocassionally when I go into "uncharted territories". **I don't care about battery, I care about mapping that area.** If I realize after a few hours of moving in that area that most of my effort was in vain, because I stood still for a few minutes somewhere and Stumbler turned off hours ago, that makes me... unhappy.

The worst of all, that motion detection can't be turned off. I have found an option in Developer section where I can increase sensitivity and timeout, but still, standing a few minutes on a tram stop will turn it off even with maximum settings.

Please, either make motion detection resume properly, or allow us to turn it off completely.

Thank you.

Mozilla Stumbler 1.5.4
Android 4.4
Motorola Moto G

**Comment by garvankeeley** [comment]
We are trying to reproduce these problems and have them fixed, but I agree with an option to turn this off. Device sensors are too variable, and I fear there will always be some devices/ROMs that have bugs with this.

Can you check the first entry in the Log screen and tell me if is says you have a 'Legacy' or 'Significant Motion' sensor? We have 2 code paths depending on the type of motion sensor.

**Comment by kparal** [comment]
Thanks for working on this. My device has a 'legacy motion sensor'.

**Comment by garvankeeley** [comment]
This is good info. What this tells me is that the problem isn't that the app isn't sensing motion -because the legacy motion sensor only reports the device not moving when sitting perfectly still.
So, the problem is that the GPS is not getting a signal, so that we can confirm the user is actually moving. This is the tricky part. 
Is it that the GPS has gone cold and is taking too long to start? We are going to do a github release today, I'll see if I can adjust the timers for this.

**Comment by garvankeeley** [comment]
Can you try 1.5.5 on github and see if it works better?

**Comment by kparal** [comment]
Sure, will try.

**Comment by kparal** [comment]
I have tested it a bit today, and the problem seems to be gone. We can close this and I'll reopen it if it appears again.

One note though: "Paused" mode seems to be really hard to achieve on my phone (with the "legacy motion sensor") with stumbler 1.5.5. I can basically trigger it if I lay my phone on the table and it doesn't move at all. But any tiniest movement of the phone (just picking in up from the table) flips it into scanning mode. So, when standing on a tram station, it's not really paused, because it wakes up just by me making a few steps or turning around. I assume you're using a motion sensor to wake up the device and re-trigger scanning mode, and therefore those developer options of motion detection (distance and timeout) don't really apply to my device with legacy sensor. I don't complain, just wanted to note that, in case this is not expected and those motion detection developer options should somehow apply even to my device.

**Comment by garvankeeley** [comment]
Thanks for your feedback this is exactly what I needed. I know where to fix the code now :).

With the Legacy sensor type, it will only pause when the device is sitting perfectly still. 

To increase the likelihood of pausing, we had an additional check that after motion detected, quickly check the location of the device, and if the reported location is unchanged, pause again. The legacy sensor could achieve battery savings by:
1) if the user put the device down overnight,
2)  or if the user was moving very little, perhaps sitting at a desk. In this case, it would wake/pause in a repeated cycle, but this would still use a fraction of the power of running full-time. 

The build you are running has that location change check turned off (#2). That is where the bug is. I'll try fix it early next week, and post another github build.

**Comment by kparal** [comment]
I have tried again today, and unfortunately I still experience the "unscanned gaps" problems.

When the display is turned on, it's true that any slight movement flips it back to scanning mode. But it doesn't seem to be the case when the display is turned off, because I had my phone in a pocket in my jacket, so it was moving slightly all the time, but still I have seen large gaps during my travel today.

It always happened when I left the street and entered a shop. I assume that means I have lost GPS signal. I have been 15-60 minutes inside the shop, then left the shop and continued traveling throughout the city.

Once, I have seen about 5-10 minute gap, once I've seen about 2-3 minute gap, and once I've seen 2-3 hours gap (most of that time spent in a shop, though, just 20-30 minutes traveling).

Every time the signal resumed, it was either caused by me waking up the phone manually, or by some event happening (a calendar notification popped up) and then I turned the display on.

Unfortunately I don't have a log, I thought I could save it afterwards, and it seems it has to be enabled in advance. I'll be able to attach it next time it happens.

Quite interestingly, it hasn't happened to me while I was waiting on a tram stop. Maybe there's yet another problem, but only related to losing GPS signal (e.g. entering a shop)?

**Comment by garvankeeley** [comment]
Related to #1415

**Comment by garvankeeley** [comment]
One bug you are mentioning is that with the screen off, the motion sensor isn't triggering. Is this with the Moto G? We have one available to test, it seemed to work fine with the screen off. 
We test like this:
- in developer settings, change the Motion Detection time window from 120s to 30s.
- wait 30s, scanning pauses, put device to sleep (with power button)
- shake device, then push button to wake, make sure scanning is not paused

EDIT: @crankycoder who is the one with the Moto G says this _is_ happening on his device (that the sensors stop working when in deep sleep)

**Comment by crankycoder** [comment]
I'd like to verify the ROM and hardware on your device - it _should_ be the same as mine, but I'm not sure if you've got the 2013 or 2014 edition of the Moto G.   

@kparal can you file a bug with 1.5.5?    Filing a bug in the settings panel will collect some firmware and chipset data and send it back to us for analysis.

In my own testing, long bus rides have ~1-2km gaps after 20 minutes on the highway. I suspect this is some combination of deep sleep and GPS lock being lost.   The device might be waking from sleep periodically because of C2DM messages from Google which might explain the restarted scans.

**Comment by Djfe** [comment]
does it get into deep sleep in under 30 seconds?

@crankycoder are you sure, that your device is next to windows while riding a bus?

at least in trains I only get GPS fixes when the device is next to the window, the GPS signal doesn't seem to be strong enough to get through the ceiling completely.

what about a test mode in addition to the simulation, that logs massively into a file on the SD card -> all sensors
to see what I'd happening

what happens if you build a debug stumbler that has an integrated wake lock call?
is the issue gone then?

**Comment by crankycoder** [comment]
WIth the Moto G - yes, this is while on a bus by a window.  Deep sleep doesn't happpen for minutes - I'm not sure what the time window is and I'm not sure what all the variables are to cause deep sleep to happen.

This seems device specific - higher end phones like a OnePlus seem to get GPS locks on buses just fine.

**Comment by Djfe** [comment]
Well so @kparal would need to wait a bit longer to egt his device into deep sleep mode

as far as I know deep sleep mode depends on the governor, so if his device is rooted then he should use a governor that allows sleep mode (not like performance or a governor that keeps the frequency at the lowest possible value without going into sleep mode)

another factor are opened apps, who might use wake locks (not too many I guess, but still)

According to several pages there is no real indicator for whether the device is being in sleep mode or not:
http://stackoverflow.com/questions/5120185/android-sleep-standby-mode/5120225#5120225

**Comment by kparal** [comment]
Hello people, I have Moto G LTE version, so I assume 2014. But I have sent a bug report from Stumbler, with title "Fake report for github issue 1394". I don't have it rooted.

>    in developer settings, change the Motion Detection time window from 120s to 30s.
>     wait 30s, scanning pauses, put device to sleep (with power button)
>     shake device, then push button to wake, make sure scanning is not paused

I tried this. The problem is that the stumbler seems to activate scanning mode every time I resume the device, even if it has not moved at all. I.e. I have it laying on the table all the time, just wait until it's paused, turn off the screen, wait a bit, and turn the display on again (carefully not to move the device). I see "Location not changing, scanning paused" for a fraction of a second over the map, and then it is gone and it is scanning. [1] I don't know whether it means that the scanning was paused for the whole time it was sleeping, or whether it simply needs to redraw once I wake it up. It works the same when I try to shake the device during sleep as instructed, again it redraws immediately after waking it up. Can we somehow debug this from the logs, using timestamps?

The above was written with stumbler 1.5.5. After that I updated to 1.6.1, and it seems to work the same.

I have managed _once_ to shake the device, wake it up, and see "scanning paused" text not to disappear, but stay. I think that suggests that my device really doesn't send motion events while sleeping.

[1] I think this is somehow related to GPS satellited. Once I wake the device, the satellite info changes (either the number next to the icon changes, or the blue dot jumps a bit, or the blue area circle changes a bit) and I think stumbler assumes it means a location change. Maybe I'm just in an unfortunate place where different satellites send me a bit different location information, and therefore it throws a wrench into my testing efforts?

**Comment by garvankeeley** [comment]
Great info!! The GPS should not be causing the unpausing, because in the paused state, the app doesn't listen for GPS. 
As you suggested, can you repeat the test and check the log screen for the "is motionless: true/false" lines. Those are timestamped. I think that touching the device sleep button is triggering the accelerometer (maybe it is ultra-sensitive), but the log will confirm that.

**Comment by kparal** [comment]
If I leave the device display on, wait for the paused state, and then try to move it slightly, the sensor doesn't seem to be that ultra sensitive. I don't trigger it if I'm careful. But almost every resume triggers it. There's probably something more in it.

Nevertheless, the log seems to indicate that the motion sensors really doesn't kick in while sleeping.
![motion](https://cloud.githubusercontent.com/assets/755451/5866134/ea097d36-a28e-11e4-9068-afe1a55d33ee.png)

In those 2 minutes, I put the phone to sleep, waited a bit, shook it properly, waited more, shoot it again, again waited, and resumed it. The resume time is the same as the last timestamp. There really were no events coming in during that time.

So it seems I'll need to disable motion detection power saving. Which is OK with me, I just wanted to make sure it's not a bug in stumbler.

**Comment by crankycoder** [comment]
@kparal ah!  Thanks!

I see your bug report.

For my own use:  Hardware is a XT1039. Stock firmware: KXB21.14-L1.46

**Comment by crankycoder** [comment]
@kparal is this still an issue with 1.7?  We've reworked a lot of the motion sensing code to handle the standard accelerometer and use network location to wake up the device.

**Comment by kparal** [comment]
I haven't used 1.7 much yet. But I have noticed that motion detected was turned back on, and I haven't seen any gaps in my coverage. So it seems this has improved greatly. Thanks a lot.
