### ISSUE TITLE
Motion Sensing V2 Planning

### ISSUE THREAD

**Issue by garvankeeley** [mozilla/MozStumbler#1449]
Next week we need to get the motion sensor working better, lets describe on a high level how we will do this. My proposal:
- Always have fallback legacy sensor running, so that if the sig. motion sensor is failing (like on the Samsung S5) we aren't stuck in paused state
- Come up with a stricter threshold for the linear accelerometer, so that it behaves a bit more like the significant motion sensor. Model it after the Nexus 5 sig. motion sensor, which reliably triggers after walking ~5 meters.
- Not on first run, but on the Power Saving Options screen have a button to 'test your sensor'. This then asks the person to stand still (the app will try confirm that), then ask the person to move (the app will try confirm that). If it succeeds, we say YAY, please turn on the motion sensing option. If it fails, we say, sorry don't use this option, please start and stop the app manually to save battery.

@crankycoder feedback?

**Comment by crankycoder** [comment]
I've reorganized the layout of the motion sensor code in #1453 to push the legacy and significant motion sensor code behind a common interface.   That patch binds only one of the significant or legacy motion sensor into the MotionSensor class, but there's no reason we can't hold onto both.

So on point 1) I agree with you that we should always have the legacy motion sensor available as a backup.

Related to point 2) - it probably makes sense to decompose the sensor inputs into a 'raw' sensor layer and a set of filters that are pluggable so that we can experiment with different strategies.  So roughly, lines 90-108 over here should be pulled out into a filter that accepts a tuple of (acceleration, timestamp).  

https://github.com/crankycoder/MozStumbler/blob/features/1428-service-in-library/libraries/stumbler/src/main/java/org/mozilla/mozstumbler/service/stumblerthread/motiondetection/LegacyMotionSensor.java#L90

One thing to note is that a speaker on sensor fusion at google mentioned that doing a highpass filter is not really that useful: http://www.youtube.com/watch?v=C7JQ7Rpwn2k

So we might want to push the existing highpass filter code down into the filter layer until we have something better.

Having that extra layer of abstraction will also help us to integrate bits like raw data from the gyro and compass and merge those datasources together.

**Comment by garvankeeley** [comment]
On the S5, at rest, the accelerometer is cycling between ~0 (correct) and ~3-5 (not correct). The latter is a pretty big motion. What is strange is that this cycle is consistent, one good, then one bad reading.

EDIT: nevermind, i am getting both accel. and lin. accel. arriving, will address this.

**Comment by crankycoder** [comment]
Do both the linear and regular accelerometer exhibit this behaviour?

**Comment by garvankeeley** [comment]
To follow up, the lin. accel. on the S5 is useless. Sitting on my desk I accelerate to 30 km/hr and then return to 0. And repeat. 
However, the accel. code is working perfectly.

**Comment by garvankeeley** [comment]
To filter false positives, check to see if the visible wifis have changed, and then do a quick check for GPS location to see that it is moving. Otherwise sleep again. Works great for me, except for wifi hotspots.
Because you might be surrounded by wifi hotspots, it will appear that your wifi APs are not changing.

**Comment by garvankeeley** [comment]
Another approach I have looked at was monitoring the GPS satellites, but not the location, and see if that might be a lower power state while paused. This doesn't work, you can't just listen for the satellites without the GPS active for location also.

**Comment by crankycoder** [comment]
We got a bug filed from a Nexus 6 user that the motion sensor had unexpected gaps.

"Stop at some location long enough to cause Stumbler to pause and then resume driving. Make sure to be driving someplace where you don't have active dots from current session so that you can see an active gap in recorded locations."

Trying to get him to hop on the mailling list to provide more information.
