### ISSUE TITLE
Service startup consolidation: the app uses binding, passive mode uses startService

### ISSUE THREAD

**Issue by garvankeeley** [mozilla/MozStumbler#1479]
Also, the passive mode startService starts the StumblerService on its own thread. 
The Mozilla Stumbler app service binding, runs the StumblerService in the main thread.

**Comment by crankycoder** [comment]
I need to read up on the AOSP code to see if there's a real difference between bindService and startService from a thread lifecycle perspective.

**Comment by crankycoder** [comment]
I dug through the AOSP code and ended up tracing the bindService and startService calls into android.app.ActivityManagerNative.  I'm pretty unconvinced there's any good reason to have this split.

I'm refactoring the MainApp and ClientStumblerService so that we run the active stumbler in it's own thread just like the passive mode.

**Comment by crankycoder** [comment]
`bindService` is required to keep the service alive.  It's bizarre and undocumented Android behavior but it's true.

See #1571 for details and evidence of the service lifecycle being different with a bound service vs an unbound service.
