### ISSUE TITLE
Geosubmit and Geolocate APIs must be used in the library

### ISSUE THREAD

**Issue by crankycoder** [mozilla/MozStumbler#1499]
To finish #1428 we need to port to use the geosubmit and geolocate API in ichnaea.

**Comment by crankycoder** [comment]
@hannosch, I've sent you emails with JSON blobs for the geosubmit and geolocate data that the new code is submitting.  Not including it here because of (minor) PII concerns.

**Comment by hannosch** [comment]
My findings based on the JSON blobs:
- accuracy, altitude and altitudeAccuracy should be floats now, they used to be ints
- remove accuracy and altitude fields from geolocate, those fields only exist for geosubmit
- cell radioType field should be called wcdma instead of umts (gsm, cdma and lte are the other strings)
- You end up sending a negative asu value, which would actually be the signalStrength in dBm. asu would be positive integers. But this might be due to Android doing the wrong thing, still worth double checking. It looks like it's correct for the serving cell (the one that has a valid cid/lac value), but wrong for all the neighboring cells.
- You send -1 value for cellId and locationAreaCode if they are unknown, can you skip those fields if they are unknown as before? I'll double check to make sure the service code actually accepts this.

**Comment by hannosch** [comment]
I looked into the cellid / lac -1 issue: The service API was wrong and required all fields. I fixed this in the service code to accept cell entries without cellid / lac fields. This isn't deployed yet.

We didn't hit this yet, since FxOS is the only client sending cell data and it only sends the serving cell and no neighboring cells.

**Comment by crankycoder** [comment]
re: ASU being encoded with signal strength or android doing the wrong thing - why pick one?  There was a bug with writing signal strength into the ASU parameter and Android appears to be giving me negative values sometimes.  Still investigating the negative values over here.

**Comment by crankycoder** [comment]
I've cut over to geolocate as of #1500
