### ISSUE TITLE
Not detecting my Location 

### ISSUE THREAD

**Issue by iamjayakumars** [mozilla/MozStumbler#161]
Hi, 
MozStumbler is not detecting my location, even i enabled the GPS. its detecting only WIFI-Access points 

Please check the image
*http://farm4.staticflickr.com/3778/10586569213_41b5c124e7_o.png

**Comment by ghost** [comment]
You are outdoors when tried? Are you grant permissions for accessing geodata in Google settings?

**Comment by iamjayakumars** [comment]
I hope i gave the permission. 
could you tell me how to check the permission settings?

**Comment by ghost** [comment]
https://db.tt/0vZtD4BJ

**Comment by iamjayakumars** [comment]
Its already enabled :(

**Comment by ghost** [comment]
Works in other apps? If not, try to check in GPS Toolbox or something similar to make sure.

**Comment by iamjayakumars** [comment]
Ya, Google Maps working fine.. 
I'm using Samsung S2 with Android 4.1.2 (Jelly Bean)

**Comment by ghost** [comment]
It's very strange. I check it on five different phones and one tablet and all works fine. MacStumbler didn't use of any kind undocumented functionality.

**Comment by iamjayakumars** [comment]
Okie, let me try with different mobile.. Thanks a lot for info

**Comment by iamjayakumars** [comment]
Its not submitting to Mozilla Location Service also. How to submit that?

**Comment by cpeterso** [comment]
@iamjayakumars: from your screenshot, it looks like your phone is not seeing any GPS satellites. If you are inside or near tall buildings, then your phone might not be able to get a GPS "fix". Is the GPS "target" icon in the status bar flashing?

Google Maps uses both GPS and Google's Wi-Fi location service, but MozStumbler only uses GPS (because we don't want to inadvertently download Google's Wi-Fi location data). If you disable your phone's Wi-Fi (so Google Maps must rely on GPS), can Google Maps still locate you?

**Comment by iamjayakumars** [comment]
Ya, my GPS flashing. I'm inside the building, let me try. once i went out...

**Comment by ghost** [comment]
Prevent from scanning while GPS is turned off.
https://db.tt/V5gGzLOO

**Comment by iamjayakumars** [comment]
Let me check, in some other places.. Thanks a lot guys :)

**Comment by cpeterso** [comment]
We should probably add some clearer instructions and error messages. <:)

**Comment by iamjayakumars** [comment]
Guys, Its working now.... I updated to latest version.. Thanks a lot..
