### ISSUE TITLE
Data points missing after Cyanogenmod upgrade

### ISSUE THREAD

**Issue by ghost** [mozilla/MozStumbler#1634]
I recently switched from Cyanogenmod 11 (Android 4.4.4) to 12.1 (Android 5.1.1) on my Nexus 7 (2012) , not an OS upgrade , a complete nuke and pave.

Yesterday I went out on my first day out MozStumbling , checked the map today and can see there are data points missing.

Screenshot of MozStumbler map , missing highlighted in red - http://imgur.com/YXqTiVm

MozStumbler map URL - https://location.services.mozilla.com/map#15/46.0923/0.2476

I always run the OSMtracker app concurrently to record a GPX track , this has captured the data that is missing from MozStumbler so its not a problem with the device.

Screenshot from OSMtracker data in GPSPrune - http://imgur.com/K7U4M5h

Both OSMtracker and MozStumbler apps have the same Cyanogenmod Privacy Guard permissions.
Location = Allowed , Keep Awake = On

**Comment by lua86** [comment]
I think it can be because lollipop. No more Dalvik... Maybe the tipical compatibility issue betwen apps and ART.

**Comment by ghost** [comment]
I was using ART mode in 4.4.4 also.

**Comment by Djfe** [comment]
The upload worked correctly?
What happened to your leaderboard: did you get more points for the stumbled route?
Are you sure that your phone recorded wifi aps or cells in this area? (it might be that you only uploaded GPS positions which are of no value for the project)
Did the rest of the track get uploaded correctly? -> does it show up on the map?

If you go there again: watch your device closely (display on, what the log says (the recorded reports), check whether the upload was successfully)
screenshots of your map after you drove through the are would be helpful as well.

you have only mentioned your OS update because this never happened to you before, right?

**Comment by ghost** [comment]
Sorry for the delay , It has been raining constantly and  had to find a route that I hadn't cycled previously.
First , the uploads are perfect , I can see my leaderboard points went from 72778 to 73001 after uploading 223 reports.
I have compared the mozstumbler map before and after my previously unstumbled route and I am seeing the purple wifi circles but no green cellular circles even though my tablet has a working cellular connection.
So it looks like the problem is with my tablet's cellular connection  , apologies for wasting your time.
