### ISSUE TITLE
A way to force unpause?

### ISSUE THREAD

**Issue by ghost** [mozilla/MozStumbler#1664]
Is there a way to force the application to "unpause"?

What happens is that it pauses appropriately when I stand still (e.g. at the office) but I want to force it to start scanning again as soon as I know I'm about to move (e.g. a quick coffee run from the office).

What I have in mind is a "Play" button on the lock screen widget.

I'm on Nexus 5 with vanilla Google Android 5.0.

**Comment by crankycoder** [comment]
@amos-stan on the Nexus 5 (or any Nexus device), the significant motion sensor should be working properly.  Is the motion detector not behaving as you would expect?  We surpress over aggressive scanning when you are _probably_ not moving to conserve battery.  You can modify the significant motion sensor threshholds in the developer options.

**Comment by gpoo** [comment]
I have seen a kind-of similar problem with a Nexus 5, however, this happen to me when I am in a car, bus, train or a ferry.  I can go for kilometers without getting MozStumbler to scan anything.

I believe this happen when it stops because I am still. Then in a vehicle, it does not detect there is movement, because the phone is still.  In such case, I wish I could force it to scan and forget about it (specially when I am going to drive).

I have 2 workarounds:
1. Whenever I am vehicle is to check if it is not scanning, press stop and start. Wait, check if scan at least once. Repeat.
2. Reboot and start MozStumbler right before I am going to start a ride of several kilometers.

The second one is just after several times riding with no scan at all.  I have tried the developer options, with no luck.  I assume I misunderstood them.  I put them back to the original settings and I started to reboot the phone.

**Comment by ghost** [comment]
@crankycoder I think the motion detector works fine and the application works as designed.
But what happens is that by default it sleeps for 20 minutes before it will notice that the phone is moving, in that time I can complete a whole coffee run or even drive home.

**Comment by ghost** [comment]
@gpoo where are the "stop" and "start" buttons you refer to?

**Comment by gpoo** [comment]
@amos-stan I meant to say the button "On/Off" in the UI.

**Comment by ghost** [comment]
@gpoo yep, this seems to do what I need, thanks.
Still would be nicer to be able to access this from the lock screen.

**Comment by Djfe** [comment]
Wasn't it possible to use the location service to detect whether the device is moving.
You probably won't even need an online connection for this. 

It would be enough for MozStumbler to notice that there are new wifi and especially cell connections that it hasn't recorded in the last 5-20mins.
Just disable GPS in energy-saving mode and scan for cells/wifis every 30 seconds/every minute (dev option like now)

**Comment by garvankeeley** [comment]
@goo that is the motion sensing causing that. Nexus 5 should have pretty good motion sensing, so our code around this sensor may be at fault.

**Comment by crankycoder** [comment]
I'm closing this as https://github.com/mozilla/MozStumbler/issues/1664#issuecomment-110999775 seems to indicate that things are ok.
