### ISSUE TITLE
Test Mozilla Location Service

### ISSUE THREAD

**Issue by iamjayakumars** [mozilla/MozStumbler#167]
Hi, I'm in India, but location shows I'm in "North Atlantic Ocean"

**Comment by g-goessel** [comment]
Same happens here (I am in France)

**Comment by cpeterso** [comment]
@g-goessel: If you are inside or near tall buildings, then your phone might not be able to get a GPS "fix". Is the GPS "target" icon in the status bar flashing?

Google Maps uses both GPS and Google's Wi-Fi location service, but MozStumbler only uses GPS (because we don't want to inadvertently download Google's Wi-Fi location data). If you disable your phone's Wi-Fi (so Google Maps must rely on GPS), can Google Maps still locate you?

**Comment by iamjayakumars** [comment]
My GPS target icon is flashing in status bar.
If i use WiFi and Test Mozilla Location Service Shows "North Atlantic Ocean"
I tried via 3G it shows "South Atlantic Ocean"

**Comment by g-goessel** [comment]
My phone is able to get a gps fix (and MozStrumbler even says 8 satellites visibles). 

It shows me the north Atlantic Ocean no matter if I'm using data or wifi.

**Comment by ghost** [comment]
MozLS api returns "not found" status in search method, there is problem.

**Comment by boinggg** [comment]
Mines blank or taupe on note 3

**Comment by cpeterso** [comment]
@boinggg: Do you have Google Play Services installed?

Are you running your own local build? When running your own build, you will need to register for a free Google API key (and add `GoogleAPIKey=whatever` to your gradle.properties file). I should really document this (and add some runtime warnings). :)

**Comment by boinggg** [comment]
No I'm using note 3

**Comment by boinggg** [comment]
Tmo rom

**Comment by whimboo** [comment]
Please see issue #130 which I have filed a while ago. This issue should be closed as dupe.

**Comment by cpeterso** [comment]
Closed as dupe of #130.
