### ISSUE TITLE
We need to add FxA support for refresh tokens as they are going live to production 

### ISSUE THREAD

**Issue by crankycoder** [mozilla/MozStumbler#1678]
OAuth bearer tokens are currently assumed to be long lived without an expiry.

FxA is rolling out refresh tokens to expire tokens at a 2 week interval initially, then much less.  The libfxa-android library needs support to issue a refresh token command.

I propose that we simply do the refresh opportunistically.  On application startup, we should try to refresh the token with the FxA server, and on upload we should attempt to refresh the token again.

We should always assume that the bearer token we are holding is correct unless the leaderboard server tells us otherwise.

In the context of the legacy leaderboard, this means that we can either :  

a) implement an FxA endpoint that handles Access Token -> Bearer token exchange and refresh token
b) Revert the FxA login code in the dev branch.

Which option do you like best? @hannosch ?  @garvankeeley ?

https://mail.mozilla.org/pipermail/dev-fxacct/2015-July/001639.html

**Comment by hannosch** [comment]
@crankycoder I'm not sure I quite understand option a. Where would this FxA endpoint have to be implemented in? The new leaderboard service?

I think you are assuming that we could switch to FxA on its own, without at the same time switching to the new leaderboard service. I'm not quite sure how that would work, as we'd have to make sure to tell people how to change/setup their FxA nicknames, so that they'd match the existing ones in the app. Or otherwise they'd loose their ongoing scores in the old system. And then when we'd switch to the new leaderboard system, they'd loose all score again. I'd rather just have one clean break with no migration story, which is easier if we do both FxA and new service at the same time.

**Comment by crankycoder** [comment]
@hannosch I concur.  I'll disable the FxA code from the dev branch of the stumbler client so we can cut a release at any time.

Closing this bug as the refresh token issue is specific to the fxa-android library anyway.
