### ISSUE TITLE
MozStumbler for iOS

### ISSUE THREAD

**Issue by ghost** [mozilla/MozStumbler#1731]
We need a MozStumbler for iOS Port :)

**Comment by lua86** [comment]
Good luck getting free-as-in-speech software into Apple Store.

**Comment by ghost** [comment]
Firefox for iOS is open source and on app store and so is VLC.

**Comment by lua86** [comment]
Haven't read apple store tos in such a long time... Besides, I think the average Ios user is less prone to something like contributing for free to something like this than the average android user is.

**Comment by hannosch** [comment]
See https://wiki.mozilla.org/CloudServices/Location/Software#iOS. The closed nature of iOS does prevent this kind of app from being developed. The API's that we'd need to collect the wifi and cell information aren't exposed to applications. Only the operating system itself has access to them.

**Comment by ghost** [comment]
Hi Hanno,

The wiki is incorrect there are several apps for iOS that already do exactly this: Sensorly, OpenSignal and Rootmetrics all on demand and in background harvest Cell Signal, Wifi SSIDS, GPS and other metrics but specifically all the data that MozStumbler collects in Android.

I'm not sure where the information was sourced but the wiki statement is incorrect.

**Comment by hannosch** [comment]
@bkerensa do you have a link to anything that specifically mentions gathering wifi bssid's or cell ids? The product descriptions of the apps you mention are all about collecting network speed /data rate information which is indeed available.

Our information is partly based on talking the team behind WiFiFoFum (http://wififofum.net/blog/) who once had a WiFi scanning app on iOS and were kicked out of the app store back in 2010. Since then Apple has done everything they can both technically and via App Store terms to prevent their app and apps like theirs to get back into the App Store.
