### ISSUE TITLE
FxA email not displayed

### ISSUE THREAD

**Issue by cascheberg** [mozilla/MozStumbler#1770]
The Firefox Account status does not show the email address after login.
That is because the FxA-JSON only contains `uid` and `displayName`, `email` is not set.
See `PreferencesScreen.processProfileRead` and `PreferencesScreen.setFxALoginTitle`.

**Comment by crankycoder** [comment]
Dang it.  This is one of those bugs where I wasn't paying close attention to the UX as we changed things.  We removed the email address visibility while building out the new leaderboard.  The FxA signin button should just indicate that the user is logged in.

**Comment by crankycoder** [comment]
Hrm.. I'm clearly misremembering this.  The FxA profile seems to be incorrectly set.  We should have a "profile:email" in there somewhere.

**Comment by jaredlockhart** [comment]
Fixed in https://github.com/mozilla-services/location-leaderboard/issues/266

This will only take effect for new users.  Existing users will not be prompted to reauthorize their FXA scope token and so will not have access to the email field, but I believe this is only shown to users during their initial sign in flow so that shouldn't affect existing users in any way?  @crankycoder

**Comment by crankycoder** [comment]
I can add a kludge that detects if the user is logged into FxA, but no email address is saved.

If that's detected, I can just throw up a notification that the user was logged out of Firefox Accounts.

**Comment by crankycoder** [comment]
Fixed with leaderboard stage and verified to be fixed when using a 'Lbstage' build directive.  This will go out in the next release of the stumbler client.

**Comment by cascheberg** [comment]
Ok, just make sure that the leaderboard update is released before the next MozStumbler version, because of #1774 ;)
