### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by ghost** [mozilla/MozStumbler#1872]
There hasn't been a new version released in over four years.
It has not been committed for over a year.
The mailing list is not used either.

Is Mozilla Stumbler dead?
Is Mozilla Location Service dead?

**Comment by jwhitlock** [comment]
Thanks @hugu48319, your questions deserve an answer. The full answer is long and complicated, and feels like it belongs in a blog post or https://discourse.mozilla.org, rather than buried in the issue tracker. I'll write that now, and link it here when published.

First, some context. There have been [big changes at Mozilla this month](https://blog.mozilla.org/blog/2020/08/11/changing-world-changing-mozilla/), in a year of big changes and challenges. I continue to be a Mozilla employee, but I have changed teams, and, like all employees, I am learning how to best support Mozilla's mission going forward. This is my own (informed?) opinion, and I may be wrong in small or large details.

> Is Mozilla Stumbler dead?

Short answer: **Yes**. 

There are currently no developers assigned to work on Mozilla Stumbler. I've reached out to former developers and talked to managers, and I do not see this changing this year. This means the most responsible action is probably to remove the application from stores. If and when it is re-staffed, it is most likely to be in the context of Firefox for Android (see https://github.com/mozilla-mobile/fenix/issues/1253), or a re-write with modern Android development practices, or both.

> Is Mozilla Location Service dead?

Short answer: **No**. 

MLS continues to support the [Mozilla mission](https://www.mozilla.org/en-US/mission/), is used in popular location libraries for Linux and Android, and is used in Firefox. I've been working on MLS (with @willkg) for a year, and will continue working on it (without Will) after this month's re-org.

> The mailing list is not used...

This is true. Mozilla has used mailing lists less and less over the years, as we've invested in other platforms like [Discourse](https://discourse.mozilla.org) and [Matrix](https://wiki.mozilla.org/Matrix). I'd like to move locations discussions away from the mailing list and toward Discourse. The formal closing of the mailing list may take longer.

**Comment by ghost** [comment]
I understood it very well.
Thank you.

**Comment by Iey4iej3** [comment]
@jwhitlock Hi, do you know that there is another app called Tower Collector which collects cell tower data for both OpenCellId and MLS? If you can reach out your colleagues, could you please inform them an opportunity for a collaboration?

The disadvantage of Tower Collection is that it does not support WiFi data collection. The issue https://github.com/zamojski/TowerCollector/issues/49 mentions some issues about WiFi collection. Maybe your colleagues could do them a favor?

**Comment by jwhitlock** [comment]
Yes, @zamojksi has been active on this and related projects, for example advocating for expanding MLS to include 5G stations (https://github.com/mozilla/ichnaea/issues/525). Thank you for linking to that issue.
