### ISSUE TITLE
Please make update notifications less annoying

### ISSUE THREAD

**Issue by whimboo** [mozilla/MozStumbler#217]
If a new version of MozStumber is available the update notifications are popping up all the time when I want to start scanning. This is kinda annoying. Can we please make it less annoying and only nag once a day or so?

**Comment by cpeterso** [comment]
My intention was for the update notification to only pop up when you launch the app, not more often. I think the notification is popping up more often because Android's application lifecycle kills our Activity often than I expected.

We should move the update notification to a different code path or add a static variable with the last nag time (so we only show the notification once a day or something).

**Comment by dougt** [comment]
Annoying so you update!  We don't want old clients in any way. ;)
