### ISSUE TITLE
Sometimes MozStumbler makes smartphone crash and restart

### ISSUE THREAD

**Issue by Valeryan24** [mozilla/MozStumbler#249]
Hello,

Since I installed MozStumbler (0.7.6 before today's update) on my phone - HTC Desire HD on CyanogenMod 11 Android 4.4, previously CM 10.2 - and when MozStumbler is in use, scanning positions, regularly my phone suddendly restarts completely.

After that all counts of MozStumbler are reset to 0, I'm unable to see when the last report was sent, if there are missing ones (locations detected, saved but not sent), how many locations / WiFi / reports previous session did...

I can not affirm without any doubt that it is MozStumbler only which causes the crash and restart, but it happens only since and when MZ works actively.

How could I help to get some logs on the phone to provide more informations, or to see if there can be conflicts with other applications running at the same time, did someone else had the same experience ?

**Comment by cpeterso** [comment]
hi @Valeryan24: I'm sorry to hear about your phone crashes! So you saw these crashes with both MozStumbler 0.7.6 and 0.8.0? How long after you start MozStumbler does your phone restart?

The problem is probably related to GPS or the frequent WiFi scanning. You might try installing a different WiFi stumbler (like [WiFiFoFum](https://play.google.com/store/apps/details?id=com.dynamicallyloaded.wififofum) or [WigleWifi](https://play.google.com/store/apps/details?id=net.wigle.wigleandroid)) to see if it also triggers the crash. If they do, then you might test disabling Android's GPS location (so Android must use Google's WiFi location service). That might help determine whether the phone restarts are related to GPS hardware or WiFi scanning. MozStumbler won't work in that mode because we insist on using only hardware GPS and not Google's WiFi location service (to avoid inadvertently downloading Google's WiFi data into our database).

**Comment by Valeryan24** [comment]
Hi @cpeterso, thanks for the answer. Yes it happened both for the 0.7.6 and 0.8.0 versions (the last one installed last week).

For the moment I was not able to identify an event or something which repetabily occurs the bug and phone restart, it happens randomly.

Sometimes just a few minutes after MozStumbler launch, sometimes it can work 2 hours during a car drive without reset...

One time the bug came just after I received a phone call (but did not answer), but all the other times without...

I will try the others WiFi stumblers you told me about to see if the same happens or not, I'll let you know.

Also, on the apps running, I have this one https://play.google.com/store/apps/details?id=com.ufcquechoisir.signalandposition which uses GPS position, too, and sends regularly quality of 3G cell signal, I will try to desactivate it.

Best regards, Xavier

**Comment by pl6025** [comment]
Hello, I've the same problem of randomly restating the phone when I use MozStumbler (0.76, 0.8.0 and 0.8.1). Today (before upgrading to 0.8.2) I was using MozStumbler for 5 minutes and when I was cheking my phone, it was restarting...
My phone : Sony Xperia X8 with GingerDX v029 (on a cyanogen ROM).
I know that I have wifi problems because I need to stop and restard wifi until it was detecting wifi, but when wifi works, it works until I stop wifi.

**Comment by tsaiian** [comment]
Hi, I have same problem using 0.10.2 on Nexus 7 
I didn't have 3G, so data send when WiFi is connect, and it often crashes at this time, after that all counts of MozStumbler are reset to 0.

Best,
Ian

**Comment by Djfe** [comment]
the reset is only UI-wise
the data still exists and will be send later ;) 
it's an UI bug

**Comment by Djfe** [comment]
#305

**Comment by Dunco** [comment]
Is there any way to force a data upload or know when it has been uploaded after the app has crashed?

I covered a few new areas yesterday but the app crashed when I tried to upload it through WiFi at the end. So far the map hasn't been updated with the points I scanned so I presume this data is lost. I haven't wiped the cache or app data.

**Comment by cpeterso** [comment]
@Dunco: when you press the "Stop Scanning" button, the stumbler will try to upload any unreported local data. If you have an available network connection, you should see the "Reports Sent" number increase and match "Locations Scanned".

**Comment by Djfe** [comment]
for me it only sends data when I enter my wifi (ab have no mobile internet) 
I can press start/stop as often as I want and then it sometimes (after a random amount of time) it uploads data collected after entering the wifi
a send button would be really helpful

EDIT: It always sends data if I press the stop button but you can only see whether it is still sending by looking at the status bar (wifi icon)

**Comment by tsaiian** [comment]
I don't have mobile internet, so it upload when WIFI available.
In my experience, 
when the WIFI scanned count > 500 , it have high chance to crash when upload, 
if WIFI scanned count < 500, definitely it will upload successfully.

**Comment by Djfe** [comment]
how much RAM does your device has normally free if you aren't using it?
because ony my phone it doesn't crash so that it sounds for me as if your phone has not enough RAM and kills the app to be able to proceed
but as explained above the data will be send later on ;) (after the next app start if internet is available)
you can simply check whether the data has been send later by looking at the coverage map after 1:30 UTC (then the rendering/update of the coverage map should be complete) or checking whether the amount of locations you have scanned is bigger now (works only if you entered the leaderboard with a nickname)

**Comment by illarionov** [comment]
It mostly depends on the VM heap size of the device. I'm also sometimes getting an OutOfMemoryException in JSON serializer when the send queue is large (on Samsung Galaxy S2 with 32MB VM heap size). The only possible solution that I see is to save send data on the disk.

**Comment by Djfe** [comment]
if you have root you should increase it because your device will run faster and smoother and your apps won't crash
my CyanogenMod based Rom uses 128mb

**Comment by tsaiian** [comment]
free RAM about 200 MB, didn't root
sadly, data didn't send after crash and restart MozStumbler

**Comment by cpeterso** [comment]
@tsaiian: Thanks for your help and patience debugging this problem! Your comment about crashing if the WiFi scanned count is > 500 is interesting because 500 scans is when the stumbler converts its scan results into JSON and may upload it. So maybe we are running out of memory when creating the JSON report.

**Comment by tsaiian** [comment]
@cpeterso : Thanks for your reply, and update.
It  work well on v0.12.0 now!!  Not crash until now :+1:

**Comment by Djfe** [comment]
@Valeryan24 is this still an issue for you or can it be closed?
there were a lot of changes in the last versions introducing a database to make sure they won't get deleted by an app restart

phone crashes/reboots can be caused by your ROM/Kernel as well
are you still using the same ROM/Kernel or have you tried something different?

**Comment by cpeterso** [comment]
@Valeryan24: if your phone is still crashing, please reopen this bug report.

**Comment by Valeryan24** [comment]
Yes, I still had last tuesday many crashes during use of MozStumbler, with the same CyanogenMod 11 Kernel, but as you say I can not ensure it is only due to MozStumbler or to a combination of reasons, or phone temperature. Just, my phone never restarts suddendly when I don't use MS...

I made a very long trip this day, but before I moved MS to SD Card in order to avoid "missing place" problem on the internal ROM phone, I also did many stops during travel, with reports always sent (3G) and counts reset to zero.

I don't know how to use logging (adb or so) and it's difficult with so few informations for you to idenify potential bug, but yes I still have crash (it was with version 0.15) sometimes - only during long sessions, when I do short measures, no problem.
