### ISSUE TITLE
More battery consumption than openbmap and opencellid clients

### ISSUE THREAD

**Issue by RyutarohYamashita** [mozilla/MozStumbler#261]
The battery consumption of MozStumbler (0.81) is several times heavier than
the openbmap and the opencellid clients. See the screenshots below.
If MozStumbler is going to be used by ordinary users, this may has to be
addressed. Otherwise the battery consumption may be non-issue.

![screenshot_2013-12-27-18-16-56](https://f.cloud.github.com/assets/6261196/1813972/0e53006e-6edc-11e3-93bb-1fe671dbf857.png)
![screenshot_2013-12-27-18-17-13](https://f.cloud.github.com/assets/6261196/1813973/0e55e0b8-6edc-11e3-89c8-78e122b4ce85.png)
![screenshot_2013-12-27-18-17-25](https://f.cloud.github.com/assets/6261196/1813974/0e57dff8-6edc-11e3-94c9-f2ac0f000e26.png)
![screenshot_2013-12-27-18-17-50](https://f.cloud.github.com/assets/6261196/1813975/0e5c4ff2-6edc-11e3-867a-ed68cb329057.png)
![screenshot_2013-12-27-18-18-16](https://f.cloud.github.com/assets/6261196/1813976/0e607366-6edc-11e3-836c-7528744ab4b8.png)

The recoding was done as the following route:
http://goo.gl/maps/Clr60

**Comment by dougt** [comment]
@RyutarohYamashita This is good feedback!  In openbmap, what settings are you using?  For example, I think there is a setting called "GPS Accuracy" -- what is that set at?  Also, are you recording wifi and cell?

**Comment by dougt** [comment]
so, what we do is when you press start scanning is that we turn on _everything_ and monitor gps/cell/wifi.  We could instead do something like, when we detect a position change, start monitoring for some period of time then stop.  This would, at least, stop most energy usage when you're not moving around.  I suspect there is a ton we can do to deeply cut energy usage.

**Comment by RyutarohYamashita** [comment]
@dougt thank you for the responses. For configutation,
opencellid: "no autoupload". GPS idle time = always running. This app does not have wifi collecting function.
openbmap: wifi & cell tower collecting. GPS accuracy = 0(?), both logging filters = 0. I am using openbmap with its
default setting, because changing configuration prevented it from collecting, which seems a bug.
Since openbmap seems a bit buggy, I am a bit doubting if it is doing what it promised.
My device: nexus 4 with stock android 4.3 (JB, rooted).

The battery saving does not seem an urgent issue, though everyone welcomes battery saving...

**Comment by dougt** [comment]
@RyutarohYamashita I am playing around with the activity service here:

https://github.com/dougt/MozStumbler/compare/activity_recognition

Basically, I have it set up so that if you move your device, we start scanning.  And, when you stop, we kill all scanning.

@cpeterso this branch is not ready for prime time, but you wanna try it out?  This does add a dependency on Google Play (again).  We should figure out what we want to do here.  This API looks like it uses the baseband modem to wake up when there is movement -- we can simulate, but we will not be able to get the power savings.

**Comment by RyutarohYamashita** [comment]
I found that power saving of openbmap is realized with some price.
Today openbmap collected wifi points 10 times fewer than MozStumbler.
See the screenshots below.
The recording was done on an express train running at 170 miles / hour
for 2 hours.

![screenshot_2013-12-28-18-30-49](https://f.cloud.github.com/assets/6261196/1817597/55eee3e2-6faf-11e3-86a9-8e2383b507bb.png)
![screenshot_2013-12-28-18-30-37](https://f.cloud.github.com/assets/6261196/1817598/5c6aff94-6faf-11e3-88c8-51902380eddd.png)
![screenshot_2013-12-28-18-30-22](https://f.cloud.github.com/assets/6261196/1817599/61202000-6faf-11e3-9f99-9c458fca8c04.png)

**Comment by hannosch** [comment]
One more thing on battery savings: Currently we upload every 20 measurements, which means that when you move around, the actual cell data connection is pretty much always active. It would be good to figure out if we can collect cell metadata without a data connection (or the high-power cell modem mode being turned on). If that's the case, we should really look at deferring the upload to much later, for example when a data connection is enabled by another app or a WiFi connection is available.

Or at least only upload if we have either hundreds of measurements or some time like one hour has past (whichever is reached first). The actual upload should then still split the data into batches of 20, but we'd upload dozens of batches after another, instead of one tiny batch every couple of seconds / each minute.

**Comment by dougt** [comment]
@hannosch if we're scanning wifi and turned on gps, i am not sure if an upload costs anything.  check out https://github.com/dougt/MozStumbler/compare/activity_recognition.  I have been running the app all day and doing a few errands and still have 75% batter.

**Comment by cpeterso** [comment]
We should definitely reduce the reporting frequency.

I increased the reporting rate from every 100 measurements to 20 measurements to reduce data loss when our network error handling was broken. Also, I recall that the server had an upload size limit (that @hannosch has increased).

**Comment by cpeterso** [comment]
@dougt: I don't know how power-efficiently they are implemented, but can we use [`LocationManager.requestLocationUpdates(long minTime, float minDistance, ...)`](https://developer.android.com/reference/android/location/LocationManager.html#requestLocationUpdates%28long,%20float,%20android.location.Criteria,%20android.app.PendingIntent%29) or [`LocationManager.addProximityAlert()`](https://developer.android.com/reference/android/location/LocationManager.html#addProximityAlert%28double,%20double,%20float,%20long,%20android.app.PendingIntent%29) APIs to approximate the Activity API on devices without Google Play Services?

**Comment by dougt** [comment]
Highly optimized.  In non Google play devices we can fall back in something like what you suggest.

**Comment by cpeterso** [comment]
Good point. Let's not let devices without Google Play Services block our primary project goals.

**Comment by Djfe** [comment]
discussion is continued in #333

**Comment by garvankeeley** [comment]
I think #1270 will change this. I can now leave the app running full time for days, with scanning on, and I have don't see major battery consumption. That said, the benefit of #1270 depends on how much you move around.

**Comment by crankycoder** [comment]
The spread in battery consumption between stumbler and other apps has closed since the 1.6 and 1.7 releases went out.
