### ISSUE TITLE
Don't reset all statistics after MozStumbler is killed

### ISSUE THREAD

**Issue by ojarva** [mozilla/MozStumbler#305]
Steps to reproduce:
- Start Scanning
- Wait for a few access points and reports
- Kill MozStumbler (task killer / restart the phone / ...)
- Open MozStumbler again. All statistics, including "Reports Sent" are zeroed.

This is really confusing, as people think their earlier reports disappeared altogether. Of course, leaderboard shows number of points, but no other statistics.

Seeing total number of locations, access points and cell towers I have sent over time would be cool.

**Comment by cpeterso** [comment]
Thanks for the suggestion, @ojarva. I think you're right that retaining the statistics after the app is killed would reduce a lot of user confusion.

**Comment by RexWheeler** [comment]
Personally I would prefer that stats are reset upon application restart. I like to see how many locations, cells, wi-fi, etc. have been processed on my current session. Perhaps having both all time stats and per session stats?

**Comment by Djfe** [comment]
Experienced an annoying issue concerning this:
drove 2000-2500 locations (was around that amount when I looked the last time at my phone, screen was off the rest of the time)

came home and checked the screen: stats reset...
the application was still open

two possible causes I can think of:
1.device run of of memory->application was killed (and restarted!?)
2.I drove by my home before heading to the garage, so the device has been in reach of our wifi for a short time and could have tried to send data, but failed (JSON conversion failure like in #249 but after 2500?)

As I wasn't able to upload the locations together with new ones later on this issue is probably not only UI-wise as cpeterso said in other comments

I hope somebody is working on the database soon to prevent such a dataloss

at least something temporary to save locations not only in memory
additional functions like displaying scanned positions accurately on the map can follow later on

**Comment by Djfe** [comment]
fixed with v.0.13.0 -> can be closed

**Comment by cpeterso** [comment]
Yep! Thanks, @Djfe.
