### ISSUE TITLE
update from 0.8.3 to 0.9.0 fails

### ISSUE THREAD

**Issue by mirakels** [mozilla/MozStumbler#315]
the installed 0.8.3 informs me there is an update to 0.9.0. It explains that existing data will not be lost. But when I allow it to install the update it says:

   'x' App not installed.
     An existing package by the same name with a 
     conflicting signature is already installed.

How to get the newer version without loosing data...?

On a side note. I found that the data  area on the sdcard contained 6 identical copies of the update (with different names). It apparently downloads the package every time I try to update. I'm sure this can be done in a more optimal way...

**Comment by Djfe** [comment]
well, the updates should probably get deleted/overwritten
for the issue you are experiencing:
I have the same problem because I installed the app from FDroid which seems to use a different build than the one on GitHub, maybe FDroid compiles apps from their sources, I don't know
atleast the version on FDroid is not up to date anymore
hopefully that will get fixed soon

I think it is possible though to save the data with apps like titanium backup (or a similar tool)
delete the app, install the new version, use titanium backup to restore the app's data

**Comment by cpeterso** [comment]
@mirakels: Did you install v0.8.3 from a source other than our [GitHub Releases page](https://github.com/mozilla/MozStumbler/releases), such as FDroid or your own local build? If so, then the Android installer will complain that the new .apk was signed by a different certificate than your installed version.

Also, the latest version of MozStumbler relies on Google Play Services library (again), so it might not be available on FDroid.

**Comment by mirakels** [comment]
I'm not sure anymore how I installed it, but I did install FDroid too as part of getting MozStumbler on my device. But I don't remember in what order I installed it.

My phone is rooted. I'm not to familiar with the android app installation process (yet), but can't I just copy the update apk to replace the existing MozStumbler apk, or will that confuse the android system?

**Comment by mirakels** [comment]
oops sorry, pressed the wrong button

**Comment by cpeterso** [comment]
@mirakels: If you want to install Mozilla's MozStumbler from GitHub, you will need to uninstall FDroid's MozStumbler build first.

**Comment by Djfe** [comment]
I switched to the github version now
didn't need to restore data, as everything got uploaded to the servers
just started the app and added my nickname again
