### ISSUE TITLE
0.8.3 - 0.9.0 update fails

### ISSUE THREAD

**Issue by JanneM** [mozilla/MozStumbler#318]
Installed 0.8.3 via f-droid. The auto-update fails on install, saying there is already a different app with the same name and different signature.

**Comment by cpeterso** [comment]
hi, @JanneM: the problem is that F-Droid signed their MozStumbler v0.8.3 build with their own certificate, but MozStumbler's auto-updater is downloading the MozStumbler v0.9.0 build signed with Mozilla's certificate. Android will prevent upgrading an app without matching certificates. To get the latest Mozilla version, you must uninstall F-Droid's MozStumbler v0.8.3 and then install Mozilla's `MozStumbler-v0.9.0.apk` from here:

https://github.com/mozilla/MozStumbler/releases/tag/v0.9.0

**Comment by JanneM** [comment]
Thanks; yes, I figured that was a likely cause and I already updated manually. But I saw in the 0.8.3 changelog an item about autoupdate fixes, so I figured I'd report this just on the off-chance that there was a problem with that.
