### ISSUE TITLE
MozStumbler has problem with wi-fi hotspot on Android 2.3

### ISSUE THREAD

**Issue by JasnaPaka** [mozilla/MozStumbler#380]
MozStumbler has some problem with wi-fi hotspot. When I enabled wi-fi hotspot on my device MozStumbler crashed. When I launched MozStumbler again I saw that information about wi-fi networks are not updated. Maybe no wi-fi scan when wi-fi hotspot is enabled? I saw no notification about that.

I can provide more informations about crash but I don't know where I can find such informations on Android. 

**Phone**: HTC Desire
**OS version**: Android 2.3
**MozStumbler**: 0.11.0

**Comment by Djfe** [comment]
(EDIT: the crash could be a bug on Gingerbread only as I was using Android 4.1.2 and as the TE said already in the title)
Doesn't crash for me but MozStumbler cannot scan for wifis it seems (which is of course understandable as you cannot enter a wifi while being a hotspot because normal smartphones only have one wifi receiver/antenna)

but I can reproduce weird behaviour:
my cell tower count stays fixed to 4 until I stop scanning again
then the cell tower counts update (the scanned counter goes upward (from 4 to 8 for example) and the visible one down to one (the used cell tower))
![screenshot_2014-02-03-21-52-43](https://f.cloud.github.com/assets/5685512/2069762/6e39b58e-8d15-11e3-894d-f2ec2228d75d.png)
![screenshot_2014-02-03-21-52-51](https://f.cloud.github.com/assets/5685512/2069766/709f5b26-8d15-11e3-9121-5298659c1659.png)

Device:
Xperia Arc S
Paranoid Android 2.57.3 (based on CyanogenMod 10)
mozstumbler v 0.11.0

**Comment by Djfe** [comment]
There should be a warning similar to the GPS warning at the scan-start that tells you to shut down your hotspot to enable wifi scanning.

**Comment by crankycoder** [comment]
We no longer crash with the wifi hotspot enabled, but wifi collections will stop happening.  Toggling the hotspot from on, to off and then back no longer crashes in at least the v1.7 release.
