### ISSUE TITLE
CDMA logging not working

### ISSUE THREAD

**Issue by tagunter** [mozilla/MozStumbler#388]
It appears the CDMA logging added through #182  merged into #71 isn't currently working. On my HTC EVO V 4G running Android 4.0.3 using Virgin Mobile USA (on the Sprint network), the app always says zero cells visible and zero cells scanned.

@hannosch told me that we only have 800 CDMA cell entries in the database (out of 500k total), and all of those from November 2013.

**Comment by tamcap** [comment]
We seem to be ignoring the CDMA code right now for some reason (actually throwing an error...), unless you are running Android 4.3+. This might be intentional or a bug... not sure. I will try to figure it out as soon as I get my hands on a CDMA device (soon).

**Comment by cpeterso** [comment]
This is definitely a bug! :( I don't have a CDMA phone, so I never saw these errors.

**Comment by whardman** [comment]
I had a look at the logcat and when it comes across a CDMA tower, it throws an IllegalArgumentException - Unexpected Network Type: CDMA  - eHRPD.  I presume CellInfo.getCellRadioTypeName() should be returning CELL_RADIO_CDMA instead.

Tried a build with that changed and got 21 cell towers scanned instead of the 3 I normally get.

**Comment by cpeterso** [comment]
@whardman: thanks for debugging that issue! I will up post a fix very soon.
