### ISSUE TITLE
Investigate undocumented WifiManager.startScanActive() API

### ISSUE THREAD

**Issue by cpeterso** [mozilla/MozStumbler#40]
This issue is forked from issue #38.

`WifiManager.startScan()` is passive: it only reports APs that happen to be broadcasting beacons. There is a hidden `startScanActive()` API that can initiate an active scan that probes APs to respond:

http://www.androidjavadoc.com/2.3/android/net/wifi/WifiManager.html#startScanActive%28%29

**Comment by cpeterso** [comment]
I tested `WifiManager.startScanActive()` but I did not any difference in the number of APs reported or the scan latency. (Both active and passive scans took about 700 ms.) Based on what I have read, I expected active scanning to report more APs and have a shorter latency (but also use more power): http://www.my80211.com/home/2010/1/11/80211-client-active-and-passive-scanning.html

`startScanActive()` is a "hidden" Android API (annotated with `@hide`), but you can access it via Java reflection:

```
Method startScanActiveMethod = WifiManager.class.getMethod("startScanActive");
startScanActiveMethod.invoke(getWifiManager());
```

**Comment by Djfe** [comment]
If this leads to a shorter latency will it scan a more accurate signal strength than the passive mode?

Does this function update the list of found aps in a more reliable way? -> remove aps which are out of range earlier?

Did this really lead to a higher battery consumption or did you only assume that?

**Comment by cpeterso** [comment]
I did not see any difference in latency between passive and active scanning, so I didn't investigate any further yet.

**Comment by Djfe** [comment]
Maybe there are no latency changes but have you tested this while driving?
Someone on the mailing list actually mentioned something that I have seen as well:
Wi-Fi APs seem to collect up to a certain point, even if they are not visible any longer. (different from cell scans which always start from zero and seem to take longer -> state switches between the one connected cell and the scanned number)
The device keeps wifi aps as it is designed to connect to them instead of delivering real-time data.
Maybe we will get more accurate estimates (whether it is still next to you) if we send requests to the aps and maybe the device realizes that you drove past an ap -> it isn't visible anymore.

**Comment by Djfe** [comment]
https://groups.google.com/forum/?nomobile=true#!topic/mozilla.dev.geolocation/ysjjdSMhGKQ
