### ISSUE TITLE
Pause scanning on ACTION_BATTERY_LOW intent

### ISSUE THREAD

**Issue by cpeterso** [mozilla/MozStumbler#41]
We should politely stop scanning when we receive an `ACTION_BATTERY_LOW` intent or `ComponentCallbacks.onLowMemory()` callback. We will definitely need to implement this if we add the always-on background mode described in issue #21.

Should we resume scanning if we later receive an `ACTION_BATTERY_OKAY` intent? Or wait for the user to manually resume scanning?

**Comment by dougt** [comment]
pause IFF you're on battery.  I think it's okay to ignore this if you're powered.

**Comment by eggpi** [comment]
Tried to get started on this today at guilherme-pg/MozStumbler@540d312eac8de475bd4d8da99a4e8daaf13c2ff4 , but for some reason I couldn't get the app to receive the broadcasts. I have only tried it on the simulator so far, by using the power command (https://developer.android.com/tools/devices/emulator.html#power).

I tried both methods of receiving broadcasts (receiveBroadcast and AndroidManifest.xml) to no avail. In that specific commit I'm sticking closely to the manifest method described in the documentation (https://developer.android.com/training/monitoring-device-state/battery-monitoring.html#MonitorLevel), but still no luck.

**Comment by cpeterso** [comment]
@guilherme-pg: you can't register for the ACTION_BATTERY_LOW intent in AndroidManifest.xml. You must call registerReceiver(). If your battery is low, starting a bunch of apps that are not already running to tell them is probably a bad idea. :)

I don't know if you can register for ACTION_BATTERY_OKAY in AndroidManifest.xml or not. For more details, see http://stackoverflow.com/a/12348778/61352

**Comment by cpeterso** [comment]
btw, I disagree with @dougt's recommendation that we ignore ACTION_BATTERY_LOW when we're on AC power. If your battery is low, then your battery is low. If your device is running a heavyweight app (such as one scanning Wi-Fi networks and GPS), it can drain the battery faster than AC power can recharge the battery. I see logcat warnings about this from Fennec.

**Comment by eggpi** [comment]
Ok, I got this to work somewhat.

It seems the BATTERY_OKAY and BATTERY_LOW broadcasts are only triggered when not on AC power -- I had to connect to the emulator and do `power ac off` before I could get my receivers to be called, even after registering at runtime with registerReceiver().

It seems to me that it's a little early to be worried about draining the battery faster than it recharges while on AC -- I would like to see if we actually come across that problem before trying to fix it. But then again, I wasn't the one who was bitten by it in the past :)

So my plan for this issue, unless you think otherwise, would be to ignore AC and simply listen for BATTERY_LOW and stop scanning when it's triggered. I don't think we should resume scanning when we get BATTERY_OKAY (feels a little intrusive to start scanning without user input, even if we were scanning before), but I can see that being configurable in the future.

Also, it seems to make sense to monitor the battery from the scanner service rather than the main activity, so it can stop itself and notify the main activity even if the app is on the background. If you agree with that, then there's a little refactoring to be made there.

**Comment by cpeterso** [comment]
Awesome! :+1: Your suggestions sound good on all points. We can ignore BATTERY_OKAY and AC intents and we should be handling the BATTERY_LOW intent in the scanner service.

**Comment by vmunix** [comment]
One data point: On my phone (Galaxy Nexus) I'm definitely not draining faster than it can charge when plugged in.

**Comment by cpeterso** [comment]
Fixed by PR #67.
