### ISSUE TITLE
Can't disable geofencing

### ISSUE THREAD

**Issue by marco-c** [mozilla/MozStumbler#423]
I've enabled geofencing, the button in the preferences now says:
"Geofence this location
Geofencing will be set at the next valid location obtained during scanning"
Now, I've changed my mind and I want to disable it, but I can't.

(Actually, I enabled geofencing just out of curiosity, it is still not clear to me what it is)

**Comment by Djfe** [comment]
geofencing allows you to disable the scanning for your current location for privacy concerns->you don't want to let people see your home on the coverage map
I think you can even choose a range but I'm not 100% sure about this right now. (at least this was a planned feature for geofencing)
I don't know whether this is a bug as I have not tested the feature myself, yet.

**Comment by marco-c** [comment]
Well, it is a bug because now I'm forced to enable geofencing for the next location that I will scan.

**Comment by Djfe** [comment]
Tested it now and found two bugs:
1. You cannot select an area for geofencing without starting to scan -> mozstumbler scans your location before the location is chosen to be geofenced->a few location/wifi aps/cell towers of the area appear in the new window "upload observations" and will be uploaded which you cannot circumvent if you want to be able to upload locations around the geofenced area
1. You cannot disable "geofence this location" until you have a GPS fix/you are located
   This is not a huge issue->you can uncheck the option after the next GPS fix and it will start scanning instantly for your current location ;)

**Comment by cpeterso** [comment]
CC @tamcap, who wrote the geofencing feature and will have more insight into the problems.

**Comment by tamcap** [comment]
"It's not a bug, it's a feature".

This code was implemented to avoid some silly problems with users changing their mind halfway through and _really_ confusing the wifiscanner / reporter. The steps are exactly as @Djfe described - if you click the "geofence here" you will not geofence until you get 2 locations from the Scanner to reliably establish your current location, also, you cannot turn off geofencing until then. As soon as the location is established, geofencing goes up, and you can also turn it on/off at will.

There is an easy partial solution that I will do a PR on soon (that makes the whole thing more user friendly) and then there is a better solution when the button actually spawns a separate thread and handles the GPS, that will most likely be implemented around February 30th. ;-)

Ability to add custom geofencing coordinates was in the first iteration of the code. It was removed when the button was added so that it would not confuse everybody.

Ability to handle more than one geofencing location can be added at a later point as well.

**Comment by tamcap** [comment]
What it also means there is no easy solution to @Djfe's bug (1) the current geofencing code uses exactly the same code that Scanner/Reporter uses.

**Comment by Djfe** [comment]
Until February 30th you could maybe make a workaround to avoid passing entries to the database until a location has been detected or tell the scanner that geofencing is active which is the current bug here
-> geofencing should be enabled without an exact location if the location is about to be set to the current location anyways ;)

**Comment by tamcap** [comment]
That will do.
