### ISSUE TITLE
Make it possible to export the gps trace only to Open Street Map ( OSM )

### ISSUE THREAD

**Issue by lhirlimann** [mozilla/MozStumbler#490]
I would love to have a button that would let me submit my gps traces to OSM.

**Comment by Djfe** [comment]
Part of #3.
Make your suggestions there ;)

**Comment by crankycoder** [comment]
OpenStreetMaps has a very minimal requirement - we just need to be able to export GPX tracks:

http://wiki.openstreetmap.org/wiki/GPX

**Comment by rugk** [comment]
Yes I also like this idea.
It would be nice if you could export the GPX files not only for OSM, but also for other uses.
E.g. you can later analyse where you walked or drove with any website or app which can read GPX files. This way you don't need another app running if you just want to view your route later.

**Comment by cascheberg** [comment]
Currently only locations that contain at least one wifi or cell observation are recorded. For the GPX export it would be much better to be able to export all scanned locations. Would it be ok to change that, and filter empty reports at a different place within the client?

**Comment by Djfe** [comment]
it would also make sense to save gps coordinates, cell scans and wifi scans differently (in general).
accuracy could be increased drastically.
right now the next report gets the wifi/cell reports even though they might be more fitting for the last report or something like that
All three scans would have a timestamp and the cell positions and wifi positions would be interpolated over the gps positions. (roughly one wifi scan would be interpolated over 5 gps positions)
this especially makes sense since the scans aren't synchronized afaik
not sure if everything below here is possible, but I would think that it is and it doesn't look accurate to me :/

```
0 secs gps scan
0,5 secs cell scan
1,5 secs cell scan
2,5 secs cell scan
3,5 secs gps scan (moved 30meters limitation)
4 secs wifi scan (started at -1 secs)
4,5 secs cell and gps scan
5,5 secs cell scan
6 secs gps scan ( driving 30 meters took longer than 1 sec again)
...
8 secs gps scan
8,5 secs cell scan
9 secs wifi scan
...
11 secs next gps scan (took longer again)
```

For the implementation accurate timestamps would be needed again (only on client side, one month accuracy isn't enough obviously) to be able to get a rough postion of the client while the wifi/cell scan has been done
(maybe it's helpful to get the speed the gps chip reports  for this in addition to the average speed we get from dividing the distance through the time)

by doing the interpolation we would get the reports and can obfuscate the timestamps there

(for the osm export I would say daily timestamps would make more sense than monthly so we would need more accurate timestamps anyways)

then we have the reports and can save them in the storage

what could be improved as well:
load reports for the map from the drive and from the ram and not only from the ram -> (to show not uploaded data points from older sessions)

the scanning speeds:
GPS should be used again every second or every 10meters (allows much more accurate interpolation) or we completely leave the meter limitation out here and merge all reports with postions in a 10m range later on (I think this limitation has been only made to reduce the amount of data the server has to save so it makes sense because we scan the gps every second anyways and only throw it away if the position hasn't changed)

cell and wifi scan speeds should be adjusted as well (maybe simply slowed down or decided after tests have been done (when does the android system reports back new hotspots and when only cached))
