### ISSUE TITLE
translations issue: observation(s)

### ISSUE THREAD

**Issue by Djfe** [mozilla/MozStumbler#497]
I'm updating the German translation right know and I'm not sure about observations:
Are measurements or scans possible synonyms, because the literal translation may not fit perfectly as not everybody will understand what the app is trying to show as observations.

Is the words meaning more clear in English or should we modify the English wording as well to fit better?

**Comment by Djfe** [comment]
Just found this, quote by Hannosch:
I've used "observations" to describe the number of underlying data points. That's the same term used on wigle's frontpage in "2 billion unique observations".
https://github.com/mozilla/ichnaea/issues/103

What does he mean exactly with data points? (locations?)

Do we need to align ourself to wigle?

**Comment by cpeterso** [comment]
Yes, this is confusing. We should pick some standard names for these concepts. We have been using terms like measurements, scans, observations, and reports inconsistently. I don't have a good answer.

**Comment by hannosch** [comment]
I've come to think about this, in the following way:

A report contains all the information you observe at any given location at one time. It's uploaded to the server as part of a batch. The upload uses batches of usually 50 reports at a time. A report is what currently gets you one point on the leaderboard.

Each report for a location contains multiple cell and WiFi network observations. An observation is always about a single cell or WiFi network. Since you observe the same cell and WiFi networks at different locations (different reports), the unique number of cell and WiFi networks is lower than the number of observations.

I realize there's likely no really good and matching translations for these terms. For a translation it's more important to be consistent in itself than be a direct translation.

**Comment by Djfe** [comment]
On my phone the number of wifis and cells in the upload observations dialog is always higher than the number of observations.
I guess this is due to them counting the number of individual scans, right? (several times the same network at the same location but at a different time)

Is observations equal to the sum of unique wifis and cells?

**Comment by Djfe** [comment]
Oh wait now I understand:
Observations=sum of all(unique wifi networks_locations(where scanned)) + sum of all(unique logical cells_locations(where scanned))

**Comment by illarionov** [comment]
For now in mozstumbler the observation is the information you observe at any given location at one time. 
The report is a set of observations (one POST request to the server, usually 50 observations per report).
It might be better to rename observations to reports.

**Comment by Djfe** [comment]
Renaming observations to reports would cause a lot of confusion as you get points for reports but not for observations and the number of observations is usually/should be higher than the number of reports.

One observation equals one unique wifi network or unique logical cell but not one location as Hannosch stated above.

**Comment by Djfe** [comment]
Actually I have found out something that makes it even more confusing

The count for send reports in the mainactivity shows the same number like the count for send observations.

We need to clear up the original strings to distinguish what is what...

**Comment by Djfe** [comment]
this discussion is now at #958
