### ISSUE TITLE
iOS Version

### ISSUE THREAD

**Issue by aaronraimist** [mozilla/MozStumbler#545]
Are there any plans for an iOS version of MozStumbler? I understand why it wouldn't go on the App Store but you could do the same thing you do with the Android app.

**Comment by Djfe** [comment]
I'm sorry but this is impossible as far as I know.
IOS doesn't give apps such an advanced access to the mobile network like android does
It is not really possible to read out those values needed to realize such an app.
My information might be deprecated though.
https://developer.apple.com/library/ios/documentation/NetworkingInternet/Reference/CoreTelephonyFrameworkReference/_index.html

**Comment by Djfe** [comment]
Ok it might be possible using hidden functions in the telephony framework

But I'm unsure whether apple would like to see Mozilla publishing an app using these.

And all developers here are mostly developing for Android I guess and don't have a mac.
So you might want to ask your question in the Mozilla dev-geolocation mailing list instead. (because this is the issue tracker for the Android client and not everybody is looking at it who is involved in the Mozilla Location Service)

**Comment by aaronraimist** [comment]
Alright will do.
