### ISSUE TITLE
Ensure locations have been received before deleting local data

### ISSUE THREAD

**Issue by Moktarama** [mozilla/MozStumbler#546]
In many poor countries, the broadband internet connections can be very patchy and unstable, leading to loss of transmitted data via wifi. I lost more than 30 000 location points that way when my phone connected to an internet box via Wifi, because the upload link was too bad and leaded the data nowhere. 

Maybe the devs could implement a function to not delete the data uploaded before confirming later on that it really has been transmitted ? 

As the data does not take much space on the phone, it would not impact the user and avoid data losses, which seems particularly important and happens usually in countries not well mapped, like ones with low quality internet and/or lower living standards than the industrialized world...

As an alternative, it might be easier just to add an option to backup then retrieve the local data elsewhere on the phone, in case the user knows he is in a country with this kind of internet problems. It would also avoid data losses.

**Comment by hannosch** [comment]
The app has various checks to ensure data has really been uploaded before removing it from the local database. If either any sort of IOError happens, or if the response code isn't the expected one (204 for submit), it should not delete the local records. I think IOError is general enough to catch all sorts of problems like failed SSL setup, broken sockets and such. These changes should be available since 0.16.

If you are still seeing lost data, than we'd need more details and any sorts of debug logs you can gather.

**Comment by Moktarama** [comment]
Thanks for the answer, it happened with the 0.17 version of Mozstumbler on a hotel wifi : one which connects me, then asks a login and a pass in the browser before letting me be really on the internet. 

I saw the number of location points being reduced (as when it is sent) before really being connected through (I was at the first step of the hotel's wifi connection), but then the number of location points sent stayed the same, and the locations never appeared on the map.

Unfortunately, I'm home now and thus cannot reproduce the bug I encountered. I'm letting the issue opened for a couple of days to see if anyone had the same problem, if not I'll close it.

**Comment by tamcap** [comment]
I have a pretty good idea what happened. Some Wi-Fi networks will generate 204 on the redirect page when requesting login. Our JSON uploads hitting ARP spoofed server redirecting into the wifi gateway went nowhere, and the local data got deleted. 
However... I thought we were using https, so I am not exactly sure how it could have happened. Maybe enough invalid certificate hits has triggered the retry counter to delete the data. @illarionov, do you think that's possible?

@hannosch the simplest solution would be to have ichnaea return something (anything, really) together with the 204 on successful submit. Is such change a possibility? I have no idea how frozen the current API is. In other case, we can analyze if the 204 return is empty (as it should be) or contains data (in which case ichnaea is being spoofed).

@Moktarama I can only apologize that such thing has happened. It's just one of those weird situations we did not control for.

**Comment by Moktarama** [comment]
@tamcap Thanks for the apology. It was kind of frustrating at the time because I had more than 30k points collected during a whole week in a country which was blank in the Mozilla location database. 

Anyway, it wasn't completely unuseful if it allows a useful correction in a future version of the app ! And I was sufficiently cautious after that to not lose locations during the other part of my trip, so Mozilla now possesses its first electromagnetic data in a west african country :-)

**Comment by illarionov** [comment]
@tamcap, I'm also not entirely sure that what is happening here. But I like the idea to ​​add an additional validation of the server that is returned code 204. We can add a validation of the server SSL certificate.
Also, we need a more smarter algorithm of resend data on failure. For example, do not delete data after 3 unsuccessful attempts to send, but additionally keep it and try to resend for at least a week. Or something like this.

**Comment by Moktarama** [comment]
@illarionov Could you make the week a month (or allowing that in the option menu) ? I mean, when a user is on holidays in a country where the internet is not readily accessible, very unstable, or has unsafe wifi (and in some countries accessing non-private wifi is quite an insurance of being robbed of private data), he can be without an internet connection (or having the same problem as I had) for the smartphone during 15 days or more.

**Comment by hannosch** [comment]
@tamcap Captive portals are painful. I thought they only used 30x codes to do redirects. A 204 code means there is no body, so anyone who implements it according to spec will not return any body.

The simple and proper thing to do is to check the SSL connection. Make sure the common name of the cert matches the hostname and the cert is based on a trusted root CA. I was hoping Android would do this by default :( We had an issue before, where our old geotrust cert was missing an intermediate cert for old Android versions and those refused the connection. After the whole heartbleed affair we got a new cert from digicert whose root CA is in Android since 2.x.

For the API change route, we already have mozilla/ichnaea#162. That's tracking the addition of a `/v1/geosubmit` API, which has the same name spellings as the geolocate API (mobileCountryCode instead of mcc, etc.). We can return a better response from that API. Going forward I want to deprecate the search/submit API's and standardize on the geolocate/geosubmit API's as that's what's used in most other clients.

**Comment by tamcap** [comment]
I might be mistaken. Android is using clients*.google.com/generate_204 (that generates a 204) to check for captive portal presence. I think I might have been mistakenly thinking it was coming from the captive portal itself. Nevertheless, that particular captive portal lost @Moktarama's work, so we need to fix that. My next best guess is the connection was dropped and a non-critical SslError generated due to hostname / certificate invalidity. But then I see no mention of SslError anywhere in refs for the HttpURLConnection, nor HttpsURLConnection (which is a child class). :confused:

**Comment by KAMI911** [comment]
Exactly same thing happened with me on WiFi with version 0.20.5. I lost around 100000 entries.

**Comment by KAMI911** [comment]
I collected again a huge amount of data: ~8000 observations more than 100000 wifi AP. This collection was offline (no way to upload during the scanning). Now I tried to upload on WiFi and the Queue was decrased but no sent data in the MozStumbler. I enabled dataplan for this but I got same problem.

**Comment by KAMI911** [comment]
It seems the problem related not the poor data connection but the huge number of uploaded data. Yesterday I tried to upload a same huge ~8000 observations more than 100000 wifi AP dataset but it failed to again. When I tried with a smaller one with 10000 it works. Is there any debug version of this app, or can you cerate one for us? Can I save database in adb (before submitting)? Or do you have other ideas?

**Comment by Djfe** [comment]
There are ideas to implement an export function for the db.
But it would need to be hided from other apps.

One question I have: why are all send counters only increasing after the upload is complete and not during the batch loop (after each batch has been uploaded successfully)?

**Comment by Moktarama** [comment]
@Djfe As long as I can remember the send counters always increased after the upload's completion. 

@garvankeeley I just read a discussion you had with other Mozilla developers about deleting the data to avoid clogging the phone's storage space : 

https://bugzilla.mozilla.org/show_bug.cgi?id=1038843#c7

I can only confirm what you wrote about the stumbling habits of Mozstumbler users, and the problems caused by the automatic deletion of the data (3 tries and/or 2 weeks ? ). 

As Mozsumbler users collect important amounts of locations points (A day on the road is 30k +, it takes often more than a minute to upload the data once back home and wifi connected), the "three tries" limit is a real issue here, because patchy wifi is very common at people's homes or hotels/other accomodations (for example I sometimes lose wifi just by going in another room in my own place).

As for the two weeks limit, it is sound for FxOS users, but not for Mozstumbler users. Even the most modest android phone can store 20 MB of location data today. Also, some people travel more than 2 weeks in a row, and you don't always have reliable wifi or a data plan readily available. Why risk losing their contributions ? 

Mozstumbler users usually are sufficiently knowledgeable to manage all that themselves. As other developers seemed pretty keened on these limits (which I understand as they have their own set of constraints), maybe Mozstumbler could include as an option the possibility to opt-out of these limits (with a disclaimer "at your own risks" ?) and avoid the risk of losing transmitted data (which is highly frustrating).

**Comment by Moktarama** [comment]
Allright, I just read @garvankeeley about the similar issue #705 : in 0.21.0 "deletions happen only if any stored data is detected to be 4 weeks old". 

I still stand by the idea of an option to drop all limits, but the change is good enough for the foreseeable future, thanks to @garvankeeley . I'm closing this issue, I'll reopen it if problems arise after the non-beta 0.21.0 will have been pushed to users.
