### ISSUE TITLE
Add an option to keep the phone's screen on 

### ISSUE THREAD

**Issue by Moktarama** [mozilla/MozStumbler#547]
To my knowledge Mozstumbler does not record data when the screen is off, as Android doesn't permit an app to do that. Could it be possible to add as an option the possibility to force the screen to stay on, like the non-open android app sensorly does ? 

It would be easier than checking the phone every 30 minutes (the longest screen wake-up time on my phone) to ensure Mozstumbler is recording. Many people don't use GPS systematically when in their cars, because they know what their trip will be.

**Comment by hannosch** [comment]
The data gathering is done in a background activity, which isn't directly tied to the front-end GUI. Those background activities should continue to gather data, even with the screen or front-end GUI being put to sleep. That's at least the behavior I'm seeing on my Nexus 4.

The background activities do react to power pressure events and shut down when the battery is almost empty. But otherwise the data gathering should continue on.

**Comment by Moktarama** [comment]
Allright, I hadn't checked since the earlier versions, it now works as you wrote. No need to turn on the screen anymore on my Nexus 5.
