### ISSUE TITLE
Allow closer zooming in map

### ISSUE THREAD

**Issue by grrrrr** [mozilla/MozStumbler#557]
Would it be doable to allow an extra level or two of zoom on the online map. I would like to better able see what areas have been missed and this is some times hard in built up areas

**Comment by tamcap** [comment]
This is something that is not currently supported by the coverage map / osmdroid combo we are using. There is a workaround available, and I will try to implement it at some point.

**Comment by stripTM** [comment]
+1
Currently I need to look at the map of https://location.services.mozilla.com/map and simultaneously google maps to know the names of the streets without coverage.

**Comment by Djfe** [comment]
@tamcap grrrrr was referring to our coverage map (leaflet) and not the Mozstumbler internal map.

@grrrrr in the past you could zoom down to street level and the points on the map where accurate, right now these dots are much bigger and fuzzy (kinda randomly placed next to the available data)
the bugzilla report that kinda started the discussion about privacy concerns: https://bugzilla.mozilla.org/show_bug.cgi?id=961429
I think there where also some discussions on the mailinglist (you can take a look at the archive of the dev-geolocation mailing list if you want to: https://groups.google.com/forum/#!forum/mozilla.dev.geolocation)
two serverside issues on github that followed afterwards, because users where complaining that they couldn't see their current progress as well as before: mozilla/ichnaea#88 mozilla/ichnaea#99
the general reason is: in regions with less data (especially in rural areas) you can basically see where the stumbler lives/workes etc. if the data on the map is not fuzzy

the only way out of this dilemma seems to be enhancing the app's map and showing the stumbled data unfuzzy and directly on it, it will be correct and there won't be any privacy concerns
tamcap is working on this right now, take a look at #336 

@stripTM you can use the app's map instead, you won't have the coverage tiles on the higher zoom levels but you can actually see street names, I think
the server developers have canceled this idea for the same privacy issue
mozilla/ichnaea#76
and as already said above: tamcap is working on some features in this departement ;) #336

**Comment by tamcap** [comment]
Ah. I misunderstood the question. The best I can offer right now is http://maps.tamcap.one.pl/. In there I use the coverage information @hannosch is willing to release publicly with a different layers and zoom setting. Coverage map is one of the very sensitive issues in this project.

**Comment by garvankeeley** [comment]
Marek, this looks great. The heat-map style is very useful.

**Comment by tamcap** [comment]
Hey Garvan, I am glad you like it. I added a basic location feature so that you can driver around with this page displayed while stumbling and have an idea where to go to get "fresh" areas. Ideally I would like to incorporate this into the native client, but the osmdroid library is a pain to work with.

**Comment by grrrrr** [comment]
Was the map (https://location.services.mozilla.com/map) changed recently? I appear to be able to zoom in a few extra steps in the last few days.  Enough for my needs certainly.

@tamcap  this is great map, thank you!

**Comment by hannosch** [comment]
@grrrrr yes, I changed the map on the website to allow a couple more zoom levels of the base map. The generated data points are still only rendered down to zoom level 13, so the blue dot cloud gets a bit blurry on the most detailed zoom levels. But I think it does indeed help to distinguish areas/streets a bit more with a tiny change to the map.js file.

**Comment by Djfe** [comment]
Can we adapt this change, Hannosch made to the server map, to the client map as well?

I'm not talking about zooming into the world itself (that is possible already) but zooming in the coverage tiles instead (even though they won't be in a higher resolution). I would like to see the coverage tiles on levels above 13 like it is now on the online coverage map.

**Comment by garvankeeley** [comment]
I am hoping for a vector overlay, which avoids raster compositing, allows for unlimited zoom, and we can stylize on the client side. Requires that stumbler vectorize (and cache) the coverage tiles (Ichnaea is backlogged with work, so we want to avoid requiring anything of that team).

**Comment by keverets** [comment]
@Djfe Your suggestion was implemented in https://github.com/mozilla/MozStumbler/pull/769

**Comment by garvankeeley** [comment]
This is fixed closing, yay :)
