### ISSUE TITLE
how to use the localized versions.

### ISSUE THREAD

**Issue by rabbihossain** [mozilla/MozStumbler#569]
Hello, i just want to know how we can use the localized mozstumbler. Users from many country submitted translation for mozstumbler. We also submitted a translation for Bengali(bn-bd) for mosstumbler. How we can use that translated version.

**Comment by Djfe** [comment]
Normally it should use the language automatically since it uses the system language.
If your system language is bn-BD and this is not the case, then there is a bug somewhere.

**Comment by rabbihossain** [comment]
@Djfe 
Thanks for notifying me. Is there any other way to force the app to show in bn-BD  language? Because, there are many mobile companies who doesn't ship bn-BD language with their android Version. That means many of us won't be able to use the localized version. 

I also found on this repository, that many people added personal mobile wifi hotspot name and public bus wifi hotspot name on the blacklist. So, I just want to know what type of wifi hostspot you want to scan through MozStumbler?

**Comment by Djfe** [comment]
Now I'm confused.
First: why should somebody delete existing languages from the Android device? (not enough free space? Not enough resources to translate the oem specific apps?)
And is Google OK with such a behavior?

I think nobody here was expecting this so there is no menu for it, yet. But it should be easy to implement, I guess.

We collect local cells and wifis that are not moving to be able to detect a user's position.
This is much faster and less energy-consuming than using GPS. The problems: you need to catch such location-specific data first if all and then you need to make good algorithms that take signal strengths into account as well.
Google is providing an in-built service for apps in Android itself, which you can choose to use instead of GPS. The difference between Google's and Mozilla's location service: Mozilla's variant is more open and Mozilla takes more privacy concerns into account -> no linking of data to a specific user/no creation of user profiles (Google Now takes guesses from their data where you live, work etc. and at which time).

**Comment by divergentdave** [comment]
Yes, some phones don't come with all the languages. I have a phone
purchased through T-Mobile US, and it only has German, English, Spanish,
French, Italian, and Korean on the language menu. It could be due to space
concerns, or because T-Mobile didn't want to translate their
carrier-specific packages into that many languages.

**Comment by Djfe** [comment]
btw. here you can get detailed information about the MLS:
https://location.services.mozilla.com/

At least you don't have any fundamental problem of understanding English, since it's the main language on your phone, right? (or are you using a different language on your phone?)

In my opinion carriers should at least keep these translations on the phone and use them as the main phone language but provide their carrier-specific packages in English-only instead. (They are in English in any case).

**Comment by Djfe** [comment]
@cpeterso What do you think about this issue?

**Comment by rabbihossain** [comment]
I don't have any issue using English language. Infact i use English language. Since there are localized version why we can't use it? That was my point.

**Comment by rabbihossain** [comment]
In our country there are some moving Wi-Fi hotspot also. Should i include that on blacklist?

**Comment by Djfe** [comment]
The reason is the decision of your carrier but a workaround should be possible.

Of course you can modify the ssid block list and commit it with new entries ;)
(the names should be kinda unique though -> not something as simple as "SJ")

**Comment by rabbihossain** [comment]
@Djfe, can you describe the workaround?  

And yes i will make a list and add them on blacklist wifi.

**Comment by Djfe** [comment]
Should have been a little bit more precise :)
Someone needs to write a workaround still
-> manual language selection in the settings is probably the best solution

**Comment by rabbihossain** [comment]
Yes I hope this can be added. Alas, i don't have any knowledge on java. So, i won't be able to help. :(

**Comment by garvankeeley** [comment]
Closing, I don't see further action on this issue likely
