### ISSUE TITLE
feature: Online coverage map - differentiate "yesterdays" logs

### ISSUE THREAD

**Issue by grrrrr** [mozilla/MozStumbler#579]
Feature request.

Currently the online coverage map only shows collected data in one color for all history.  I would like to suggest having two color levels

color 1: all new points added at the last generate time, essentially all points added "yesterday"

color 2: all other points older than "yesterday"

Admittedly there would be no real world benefit to this other than informational.

**Comment by Djfe** [comment]
You should open such a request in the server-side project instead ;) :
Mozilla/Ichnaea

**Comment by VolMi** [comment]
```
Admittedly there would be no real world benefit to this other than informational.
```

Au contraire to this. It will be helpful to see where data are 5+ years old already. But, assuming Ichnaea does not throw away time stamps, that feature can be implemented gently, e.g. after total world domination.

**Comment by Djfe** [comment]
One general thing:
We can only use the upload timestamps (might be only a daily),
because the real date (when the data was collected) is even cut down to the first day of each month 0:00:00
This has privacy reasons as we don't want to be able to see someone's weekly/daily/hourly schedule including the location
-> such informations are highly private

The upload date is not private though as mozstumbler has an internal database so that you can upload data later.

As this feature request is there to be able to see your progress on stumbling data:
There are plans already to enhance mozstumbler's internal database and show detailed data on the internal map -> this should show your progress even better

**Comment by grrrrr** [comment]
closing as project is no longer active - https://discourse.mozilla.org/t/retiring-mozilla-stumbler/75206
