### ISSUE TITLE
Export settings on SD card

### ISSUE THREAD

**Issue by sabas** [mozilla/MozStumbler#597]
While uninstalling the app, the user data should be preserved (nickname for example).

**Comment by Djfe** [comment]
Even more interesting for later on
-> preserve database + geolocation settings from deletion on uninstalling
(later if the database is used to display the user's data on the map) 

MozStumbler could use the SD Card to save it's data on.
Like titanium backup: the app backups are kept on the SD card even when flashing new roms.

**Comment by Djfe** [comment]
You should edit the title though since the app cannot edit the uninstallation dialogs.
Maybe "save settings on SD card".

Thinking about it: I'm not too sure if users who really want to uninstall the app will feel great if mozstumbler data remains on his/her SD card.

It's a shame that Google doesn't provide such a function (keep user data) inbuilt into Android.

**Comment by sabas** [comment]
Done, I was wondering the same thing..

**Comment by crankycoder** [comment]
It's problematic to find a location to write to storage across the variants of Android hardware and software.  I don't think it makes sense to use up storage if the user has explicitly uninstalled our application.  We currently do versioned upgrades preserving the old preferences where possible.

I'm closing this as I don't see any user benefit.
