### ISSUE TITLE
Upload lost

### ISSUE THREAD

**Issue by KAMI911** [mozilla/MozStumbler#651]
I did a whole day long data acquire and I used Wifi at the end of the scanning. The numbers of the events in the queue decreased but number in Sent field did not increased? What happened? Is it possible to reload those data again? Or can you find them on the Mozilla server? I got around 100000 scanned WiFi Access points.

**Comment by garvankeeley** [comment]
What happened is a very good question. You can't reload the points, and because the data is collected and sent anonymously, there is no way to know on the server that your data was sent. 

I am reviewing this code, here are my notes on that:
- the deletion of records happens only if cleanSend() succeeded:
  https://github.com/mozilla/MozStumbler/blob/14fdfea5449c3f32ea0c1398ab91b9c335dc36e2/src/org/mozilla/mozstumbler/sync/SyncAdapter.java#L131
- The code here has a minor problem, since the else statement is never called:
  https://github.com/mozilla/MozStumbler/blob/14fdfea5449c3f32ea0c1398ab91b9c335dc36e2/src/org/mozilla/mozstumbler/sync/SyncAdapter.java#L144. If batch == null there is an earlier break in the loop.
  This error is benign however.
- Could something happen where the query for the next batch of 50 is malformed:
  https://github.com/mozilla/MozStumbler/blob/14fdfea5449c3f32ea0c1398ab91b9c335dc36e2/src/org/mozilla/mozstumbler/sync/SyncAdapter.java#L115

**Comment by garvankeeley** [comment]
@KAMI911 
1) What device are you on? 
2) Were you on stumbler v0.20.5?
Thanks.

**Comment by garvankeeley** [comment]
Similar bug https://github.com/mozilla/MozStumbler/issues/546

**Comment by KAMI911** [comment]
My device is Samsung Galaxy Young (GT-S6310 / Android: 4.1.2)
I am using the latest version: 0.20.5.

**Comment by garvankeeley** [comment]
I don't see anything in the upload code, so the next thing to look at is the UI-related code for showing these stats. Hopefully, the bug is in the stats reporting, not the uploading.

**Comment by KAMI911** [comment]
Hi,

I wrote my today's experience to #546 so I aborted to upload, can I save the data  (via adb) and process/reload it later?

**Comment by Djfe** [comment]
@garvankeeley take a look at the statistics code or rather the code that updates it
-> it only updates the sent entries after the upload has been finished and not inbetween (after each batch) or at the start of the app (in case you exited the app before the upload has been finished)

**Comment by garvankeeley** [comment]
Closing, see Issue #681 regarding the fix for this -or what we believe the fix to be :).
