### ISSUE TITLE
Make it movable to the external storage

### ISSUE THREAD

**Issue by naoliv** [mozilla/MozStumbler#709]
Could MozStumbler be made movable to the external storage (SD card)?

**Comment by crankycoder** [comment]
This would end up complicating our storage layer for tiles and stumbler reports.  Many newer devices don't support SD cards.  There is also no standard API to access the external SD card.

**Comment by naoliv** [comment]
Isn't it as simple as setting `preferExternal` in http://developer.android.com/guide/topics/data/install-location.html ?

**Comment by crankycoder** [comment]
Oh, this is actually worse than I thought.

We don't want to install on external storage because we do at least 3 of things listed under "Applications That Should NOT Install on External Storage":
- Stumbler is a Service
- listen for ACTION_BOOT_COMPLETED
- We use Alarm Services to schedule file uploads to ichanea.

**Comment by lua86** [comment]
Besides, why would anyone move such a lightweight app to the sdcard? I see less than 3 megabytes of benefits against a lot of counterfeit.

**Comment by naoliv** [comment]
@crankycoder understood!
@lua86 when I asked this I had a device with a very limited internal storage
