### ISSUE TITLE
uploads consistently failing

### ISSUE THREAD

**Issue by grrrrr** [mozilla/MozStumbler#713]
phone: Samsung Galaxy S4
ROM: Cyanogen Mod 11 M8
MozStumbler: 0.20.9

In the logs I see

```
Error submitting: org.mozilla.mozstumbler.service.AbstractCommunicator$HttpErrorException
```

This gets repeated several times (3+)

Then as per other tickets, the collected tracks get deleted

Previous version 0.20.8 uploaded with out issue

**Comment by garvankeeley** [comment]
Thanks for the info. Perhaps I am supposed to be ignoring all HTTP errors, and only up the retry count on other forms of error. (The 'retry count' has a limit, then the code deletes, the code will still try to upload old data on next sync without increasing this number).

**Comment by grrrrr** [comment]
@garvankeeley I do not believe this is the same issue as the retry limit one.  This was consistently failing to upload where 0.20.8 worked fine.

Having tested 0.21.0 Beta, upload appears to be working again.

**Comment by Djfe** [comment]
0.21.0 should have fixed this since there were a lot of things rewritten in the upload code

I think the limit has been removed and the uploaded doesn't use android's sync method anymore but another more reliable method instead (look at the changelog part with "alarm clock")

The reason why this sounds similar to the limit thing is that it deletes the record after exactly 3 http errors
You said 3+ http errors.

**Comment by grrrrr** [comment]
@Djfe yes, 3+ but it there were definitely more than 3 tries at times, though highest I was was 5.

0.21.0 sync has been working like a charm and a lot faster too.  As it's fixed in this release I'm going to close this ticket.

**Comment by garvankeeley** [comment]
Thanks for feedback!
