### ISSUE TITLE
Add Ono Wifi to blacklist

### ISSUE THREAD

**Issue by logos88** [mozilla/MozStumbler#714]
The internet provider Ono gives free internet for their users in big cities. Their SSID is _AUTO_ONOWiFi

https://red.onowifi.es/

**Comment by Djfe** [comment]
Is this even a moving wifi? for example a bus
if not then this doesn't need to be excluded as the wifi aps don't move -> they can be used for guessing one's location without any problem

**Comment by logos88** [comment]
It is not moving. But there are a lot of them with the same name in different cities. If there is no problem with that then nothing. Sorry.

**Comment by Djfe** [comment]
with the same name (SSID) but not with the same "id" (BSSID), which is based on the Mac Adress of the Wifi AP. (the mac address is unique all over the world)
Ichnaea/MLC uses the BSSID obviously since it will never change as against the SSID, which you can freely change as the APs owner.
You can close this thread now.

**Comment by logos88** [comment]
What ono does is using the home and comercial routers to give this additional source. For instance, my router has two signals to connect, _AUTO_ONOWiFi and the personal mine, but both come from the same router.

**Comment by Djfe** [comment]
both aps are using different BSSIDs, else it wouldn't work , I think
thx for trying to contribute to MozStumbler though ;)
