### ISSUE TITLE
MapActivity: show my gps track, and equivalent MLS track

### ISSUE THREAD

**Issue by garvankeeley** [mozilla/MozStumbler#733]
Show the gps track so I know where I have been. Also show the MLS track so I can see the value of my contribution (and I can see where we have greater error and need more stumbling). With repeated stumbling I should see the MLS track improve over time, which is a valuable indicator. 
Also, Firefox OS QA can use this information to better understand MLS location error.

Sorry, my colours are swapped on my drawing,  the GPS track should be blue.

![screen2](https://cloud.githubusercontent.com/assets/5495083/3716336/b2043f00-1609-11e4-8b25-486aebc42a00.jpeg)

**Comment by Djfe** [comment]
I noticed a bug in 0.21.0:
![screenshot](https://cloud.githubusercontent.com/assets/5685512/3906737/c57d532a-22f5-11e4-96de-cc3595b9d1f7.png)

The map page only loads current points and connects them -> it is possible that it misses some if the devices screen was turned off
->it will connect the last and the next point and doesn't care about the data that was collected inbetween

if you reload the map page it rebuilds the complete track so that the correct track is shown

**Comment by garvankeeley** [comment]
Great report, with this info it will be easy to fix

**Comment by crankycoder** [comment]
Closed as of #817 landing
