### ISSUE TITLE
Marker for position is too big

### ISSUE THREAD

**Issue by Gitschubser** [mozilla/MozStumbler#750]
Hmm, i think the marker for the position could be smaller.

**Comment by garvankeeley** [comment]
On my screen it is 25% smaller than the marker on google maps, can you screenshot it? Maybe there are screen size issues we need to consider

**Comment by Djfe** [comment]
The way it looks on my screen:
![2014-08-01 22 48 41](https://cloud.githubusercontent.com/assets/5685512/3787976/14938c60-1a48-11e4-8015-d7a1aecfdc49.png)

**Comment by keverets** [comment]
Likely due to drawing based on px rather than dp.

**Comment by Djfe** [comment]
even on my galaxy tab 3 10.1 (1280x720px) the pointer is bigger than the pointer of Google Maps
the track could be thinner, too in my opinion
and the pointer and the track are not transparent, which will hopefully change in the future so that you are able to read street names below the track and and the pointer

**Comment by garvankeeley** [comment]
I believe this to be fixed by #817
