### ISSUE TITLE
Task Notification list item: The stop function on this is not in sync with the app 

### ISSUE THREAD

**Issue by garvankeeley** [mozilla/MozStumbler#761]
The task notification list item has stop button when expanded, this is not in sync with the state of the app. It says "[X] Stop Scanning" when the app is currently stopped.

**Comment by garvankeeley** [comment]
Originally reported as issue #710.

**Comment by ioana-chiorean** [comment]
I entered a issue earlier here https://github.com/mozilla/ichnaea/issues/293 . probably wrong place :S 
Thanks for following up my comment with this issue.

**Comment by Djfe** [comment]
#746 is also part of this issue, I think

And what's also irritating:
Since one of the latest versions you cannot see whether there is a GPS fix or not (it still shows x/y satellites if I deactivate GPS in my status bar) 
This was different before:
No value or a "-" instead of "x/y"
EDIT: this has been listed as #685 already

**Comment by crankycoder** [comment]
Tapping repeatedly on the 'X' in the notification pulldown eventually works.  The UI shows that the scanning has stopped, but the stumbler stays in the notification area.  This is different than hitting the stop button which stops scanning _and_ removes the stumbler from the notification pull down.

**Comment by crankycoder** [comment]
closed in #782
