### ISSUE TITLE
weird behaviour

### ISSUE THREAD

**Issue by Djfe** [mozilla/MozStumbler#764]
What could be the reason for this?:
![2014-08-08 17 52 34](https://cloud.githubusercontent.com/assets/5685512/3953793/83a07146-26ef-11e4-8629-639c4b57c375.png)

And why are the numbers for wifis and cells in the upload window in general so low now?
Is the upload window now displaying only the number of unique wifis and cells?

The general question is: why are there differences between those numbers?
My guess:
maybe I was driving faster than 10m/s, so maybe the device caught a glimpse of those wifis/cells between the GPS refreshes and so they are not recorded into the database.

For the cells this theory doesn't make too much sense though, because their radius is so much bigger.
same goes for wifi aps: it doesn't make much sense since Wifis are normally longer in the "caches" of Android in case they reappear (no real-time scan, rather a scan that tries to get and keep as much as possible(at least that's my theory, why the number of wifis often goes up, while moving fast, but goes down much slower, mostly while standing still))

EDIT: something similar happended on my tablet as well (although I cannot prove it, since Upload only on wifi wasn't checked like on my smartphone, so maybe it uploaded something in between, but I don't think so because since the alarm upload method got introduced it only starts uploading automatically on wifis but not on mobile network connections)

**Comment by Djfe** [comment]
Ok i have further observed the behaviour
For my Samsung Galaxy Tab 3 10.1 everything is fine, the number of cells is so low, because the device doesn't save neighbouring cells (at least mozstumbler shows that it only sees one cell at a time), the number of wifis was so low because I drove on a freeway/highway

For my Sony Ericsson Xperia Arc S: unlike my tablet it shows neighbouring cells and the numbers of wifis is roughly the same, BUT:
It only scans neighbouring cells while the sceen is on. I'm not sure whether this behaviour is expected/a mozstumbler bug/device(hardware/rom) specific, so I want to ask you now, what the easons could be.

**Comment by cascheberg** [comment]
I noticed the same problem with MozStumbler v0.21.0. I am using a Nexus 4 with Android 4.4.4.

Example result after one scan, I was walking, within a rather small area, woods and urban.
main screen scanned vs. upload dialog queued:
Obervations: 548 vs 548
Cells: 47 vs 64
WiFi: 335 vs 46
I wonder if this is just a bug with displaying the correct number, or affects the collected data.

I tried to find out more about this bug and started walking around slowly and kept watching the stats.
At the beginning both, queued Cell and WiFi numbers, were permanently increasing and decreasing, roughly corresponding to the number of currently visible Cells/WiFis.
Stopping the scan (and removing the app from the list of active apps) usually deleted all of the few (< 50) observations (no upload because data connections were disabled).
If data was saved during the app restart, and I continued to scan, the number of queued Cells/WiFis was approximately #saved + #visible.
Again, stopping the scan and killing the app did not save the few new observations, so only those observations that had been saved previously remained.

**Comment by garvankeeley** [comment]
Thanks for the report, it is a display bug, collection is ok.
If the app is killed, you can lose in-memory scans that haven't been persisted, this is by design to reduce the frequency of disk I/O.

**Comment by Djfe** [comment]
Ok is it easy to fix?
If I press stop scan no scans will be lost, right?

How often will MozStumbler attempt to save collected data?

**Comment by garvankeeley** [comment]
The wrong numbers being reported should be easy to fix.

If you press stop no scans would be lost. If the app is destroyed gracefully, no scans would be lost. If the app is destroyed unexpectedly your last scans could be lost.

It saves the collected data when 50 scans have happened , or every 3 minutes.

**Comment by Djfe** [comment]
ok thx ;)

**Comment by Djfe** [comment]
hopefully this behavior  gets fixed before the next release

it could cause quite some confusion, if the numbers are that low
(I sometimes see 0 wifi aps in the queue even though I definitely scanned some...)

**Comment by cascheberg** [comment]
This problem still occurs in the v0.30.0 release. Even the increase of the sent data values after uploading seems to be rather random.

**Comment by Djfe** [comment]
I guess this has been fixed in 0.40.0, right?
I'm going to close this now.
If somebody thinks that it's not fixed, yet, then I will open it again.
