### ISSUE TITLE
Enable hardware acceleration

### ISSUE THREAD

**Issue by garvankeeley** [mozilla/MozStumbler#778]
I find the map view is much smoother panning and zooming with this on. Is there a reason it is off?

**Comment by cpeterso** [comment]
Not that I am aware of.

**Comment by Djfe** [comment]
You were the one who pushed the commit ;) 
See #585.
It got disabled to reduce the memory usage of mozstumbler.

Maybe needs further investigation.

**Comment by garvankeeley** [comment]
Oh yeah :), thanks!
20+ MB RAM jump? That is rather significant.

**Comment by Djfe** [comment]
Might be helpful:
http://forum.xda-developers.com/showthread.php?t=1643722

We should compare hardware acceleration on/off on several devices to evaluate on using or discarding it.

**Comment by garvankeeley** [comment]
This says it increases RAM by 2MB: http://www.extremetech.com/computing/107995-the-truth-about-hardware-acceleration-on-android

**Comment by garvankeeley** [comment]
15 MB RAM increase for me on Nexus 5:

![screenshot 2014-08-25 20 40 21](https://cloud.githubusercontent.com/assets/5495083/4038659/a8910ee6-2cb9-11e4-8c51-10b8a140e9ac.png)

**Comment by Djfe** [comment]
@garvankeeley it says 2-8mb for the opengl driver alone...
so maybe the app itself needs more ram, too

also: the article is from 2011 and about ics, not Kitkat, so there are maybe differences (like higher ram usage, but better smoothness, but this is just a guess)

what I'm wondering about: of course Android uses Multitasking, but the app runs in  the background in your screenshots -> so that it probably needs no hardware acceleration at that time

is there a way to check this using adb while the app is running in the foreground?

**Comment by garvankeeley** [comment]
After comparing with this on/off and running the app for various periods, and also comparing the apps RAM use to other apps, I can't see any issues with having this on. My comment about a 15 MB RAM increase is incorrect, if I run the app a bit longer with hardware acceleration off, the ram usage difference is negligible.
