### ISSUE TITLE
MozStumbler Not Available for Nexus 7

### ISSUE THREAD

**Issue by Zeriuno** [mozilla/MozStumbler#779]
I would like to contribute to the Mozilla location effort, but sadly I can't install MozStubler on my Nexus 7: Fdroid marks it as not available. Could you please solve it?

**Comment by Djfe** [comment]
Fdroid builds MozStumbler on it's own, so that it doesn't have the API key for the map Mozilla provides in its own builds. -> you will see a different map
you get Mozillas builds here: https://github.com/mozilla/mozstumbler/releases
they will inform you about updates and download and install them automatically if you want to update
->you don't need the fdroid version and you will stay up to date (fdroid takes some time to notice that there is an update available ;) )

about FDroid itself:
https://f-droid.org/repository/browse/?fdfilter=MozStumbler&fdid=org.mozilla.mozstumbler
you can see that it provides the current version ;)
I don't know why v0.20.9 shouldn't be available to Nexus 7 users.
v0.21.0 is a beta so it's correct that it isn't listed at FDroid, yet.

**Comment by Zeriuno** [comment]
Thanks for letting me know about the updates system! Going to download it right away. Could you please add a checksum as well with the realeases?

**Comment by Djfe** [comment]
Do you think your download will corrupt or are you fearing a man-in-the-middle attack?

(This was just a question of mine. I'm not working for Mozilla so this is up to them.)

**Comment by Zeriuno** [comment]
Both. Obviously if the downloaded file is corrupted you'll eventually
find out when you fail to install it.

Let's just say that I think everyone should do checksums and everyone
should be allowed to do it.

**Comment by Djfe** [comment]
A man-in-the-middle attack could also change out the shown checksum...

But since Github uses a really good ssl encryption (calomel ssl shows 100%) I don't think a man-in-the-middle attack would be successful

a checksum check in the integrated downloader would be needed then as well

**Comment by crankycoder** [comment]
I'm closing this as this appears to be a problem with F-Droid.  The stumbler installs just fine on the Nexus 7.  Checksums will be sorted out when we move to the Play Store.

**Comment by Zeriuno** [comment]
Well, honestly I don't think it should be closed until the problem with F-Droid is identified and resolved: is F-Droid allowing to install it now? As far as I know no, it isn't.

**Comment by helix84** [comment]
Not resolved yet as of version 1.0.0.0 Google Play or 0.30.0 in F-Droid.
