### ISSUE TITLE
UI: First run experience

### ISSUE THREAD

**Issue by garvankeeley** [mozilla/MozStumbler#794]
As part of the product experience: the first-run should:
- have a legal dialog (if needed)
- brief explanation of the app (VERY brief)
- door hangars on key buttons/icons to explain what they do

**Comment by Djfe** [comment]
- #430 
- brief explanation/door hangers should include an explanation of the geofencing function
  *a dialog that asks whether the user wants wifi only for uploading ( #555 )
  *maybe a dialog whether the user wants to be listed in the leaderboard (so that he can enter his username)

@cpeterso has posted two things somewhere he wanted to see in a first run dialog, but I don't find it anymore, maybe he can say if he is missing something or not

Edit: this could be used for the "door hangers":
http://www6.pcmag.com/media/images/344565-guided-tour.jpg

**Comment by Gitschubser** [comment]
First-run could include the changelog after a update.

**Comment by Djfe** [comment]
Thx that was the one that was missing ;)
(the one @cpeterso listed somewhere)

**Comment by crankycoder** [comment]
Geofencing is no longer a feature. 

Wifi only for uploads is now defaulted to true. 

We don't want to clutter the first run dialogue with too much text at this point. 

Adding a change log to the first run is a good idea though, let's do that post 1.0.

**Comment by crankycoder** [comment]
@cpeterson is assigned the google play store description.  Let's just use a summarized version of that text for our first run description.

**Comment by garvankeeley** [comment]
Closing, we have a first run dialog now, no further action planned ATM on this.
