### ISSUE TITLE
Button to check for updates manually

### ISSUE THREAD

**Issue by sawrubh** [mozilla/MozStumbler#796]
There should be a button in "About MozStumblr" which should allow to check for updates.

**Comment by Djfe** [comment]
why?
there is an inbuild update task that searches for updates on the app start.

I assume that you are a new user, else you would have seen the window appear already.

at the moment 0.20.9 is the current version and there are no issues with it except the "Unfortunately MozStumbler ahs stopped working" bug which is not a big bug.

0.21.0 is a beta because so much code got changed that some experienced users hsould test it first.

There are some bugs in the new features, also not too big.

It's up to you whether you want to update to 0.21.0 or not, in the next weeks a new version (probably a stable version (1.0.0) will be published, you just need to wait a little bit)

there will be a second beta as well (fixing those small bugs) before that happens though.

The only reason this might stay open is: #766 

because then the user could force the application to search for updates if the setting (only on wifi) is enabled and the user is using a mobile network.

**Comment by Gitschubser** [comment]
I would allow both, 
- check updates manually and 
- check updates automatically.
  
  I use v0.20.5 and always the app asked for the new update. ;-(

**Comment by Djfe** [comment]
Why don't you update, is there any reason?

**Comment by Gitschubser** [comment]
With v0.21.0 it is not possible to locate me via wifi or cellid and i want that feature!
When i want to show my position via GPS i use Osmand.

**Comment by Djfe** [comment]
but that has nothing to do with this issue
and you reported it already in: #747

**Comment by Gitschubser** [comment]
I can't follow you.

You asked me: Why don't you update, is there any reason?
I answered: With v0.21.0 it is not possible to locate me via wifi or cellid and i want that feature! .....

After i have tested v0.21.0, i downgraded back to v0.20.5 and opened #747.

**Comment by Djfe** [comment]
oh I'm sorry... definitely my fault
I totally missed what I had said before and only looked at the thread's first entry at the top

ok that's a valid and good reason but I'm not sure whether this will be changed before 1.0 release

**Comment by crankycoder** [comment]
Updates come down automatically if you're on the Google Playstore or F-Droid.  We've designated the github release channel for early adopters and testing.
