### ISSUE TITLE
API level 11 required?

### ISSUE THREAD

**Issue by dougt** [mozilla/MozStumbler#84]
Is Context.MODE_MULTI_PROCESS only in 11?

Scanning MozStumbler: ..........
src/org/mozilla/mozstumbler/Prefs.java:128: Warning: Field requires API level 11 (current min is 8): android.content.Context#MODE_MULTI_PROCESS [InlinedApi]
        return mContext.getSharedPreferences(PREFS_FILE, Context.MODE_MULTI_PROCESS | Context.MODE_PRIVATE);

**Comment by cpeterso** [comment]
Where did you see that warning? Yes, `MODE_MULTI_PROCESS` was added in API Level 11. I had assumed we didn't need to check the OS version at run-time because earlier OS versions would ignore flag bits they did not recognize. If this is a compile-time warning, I'm not sure a run-time check would suppress the warning.

The docs say `MODE_MULTI_PROCESS` "was the legacy (but undocumented) behavior in and before Gingerbread (Android 2.3) and this flag is implied when targetting such releases. For applications targetting SDK versions greater than Android 2.3, this flag must be explicitly set if desired."

https://developer.android.com/reference/android/content/Context.html#MODE_MULTI_PROCESS

**Comment by dougt** [comment]
running lint found this

// Doug Turner
