### ISSUE TITLE
Upload issues: add a "Resume Upload" Button

### ISSUE THREAD

**Issue by QuandHarryViste** [mozilla/MozStumbler#860]
Some of my data are sometimes stuck in the app, because the upload seem never complete (while my home WiFi is OK for other apps).
If I reboot the phone, data are lost.
A "Resume Upload" function would help.

**Comment by garvankeeley** [comment]
Thanks for the report. This is surprising, since the app saves data as files on disk and deletes them only when upload complete. You may have a few recent collections held in memory that can get lost if the app is killed suddenly. Can you provide more detail as to what you are seeing (some screenshots maybe).

**Comment by Djfe** [comment]
it could help, if the stumbler would save observations to the file every x seconds instead of every x reports

**Comment by crankycoder** [comment]
Resume upload is no longer necessary as we journal all in-memory records to storage on low memory pressure or application close.  Those records are uploaded once the app is restarted.  If an upload gets 'stuck', the network connection just times out.
