### ISSUE TITLE
Wifi count seems to be off by one 

### ISSUE THREAD

**Issue by crankycoder** [mozilla/MozStumbler#867]
I'm in an area where I'm sure there are no wifi access points. The count is still showing 1 though.

**Comment by garvankeeley** [comment]
check the on-device scan, is that empty?

**Comment by narfg** [comment]
I can confirm that the WiFi count sometimes shows 1 in completely remote areas and almost never goes to 0. However, I don't think it's an error in MozStumbler because the number seems to be consistent to the WiFi scan in Android. I guess that either Android or my phone's WiFi driver (Nexus 5) seem to be reluctant to empty the list of available networks.

**Comment by cascheberg** [comment]
Same for me on a Nexus 4 (Android 4.4.4). Sometimes the count does go down to zero, sometimes it does not.
